// frontend/src/components/CookieConsentBanner.tsx
import { useNavigate } from 'react-router'
import { useAnalytics } from '@/hooks/useAnalytics'

export function CookieConsentBanner() {
  const navigate = useNavigate()
  const { consent, dntEnabled, setAnalyticsConsent, trackEvent } = useAnalytics()

  const visible = consent === 'pending' && !dntEnabled
  if (!visible) return null

  function acceptAnalytics() {
    setAnalyticsConsent('granted')
    trackEvent('analytics_consent_updated', {
      consent: 'granted',
      source: 'cookie_banner',
    })
  }

  function declineAnalytics() {
    setAnalyticsConsent('denied')
  }

  function openPrivacySettings() {
    navigate('/app/settings/general')
  }

  return (
    <div
      className="fixed bottom-4 left-1/2 z-50 flex max-w-lg -translate-x-1/2 items-center gap-4 rounded px-6 py-4 shadow-lg max-md:flex-col max-md:items-stretch"
      style={{ backgroundColor: 'var(--color-surface-container-low)' }}
      data-testid="cookie-consent-banner"
    >
      <div className="min-w-0">
        <strong className="block text-sm" style={{ color: 'var(--color-on-surface)' }}>
          Analytics preferences
        </strong>
        <p className="mt-1 text-sm" style={{ color: 'var(--color-on-surface-variant)' }}>
          Ace can use privacy-focused analytics and optional session recording to improve product
          quality.
        </p>
      </div>
      <div className="inline-flex flex-wrap items-center justify-end gap-2 max-md:justify-start">
        <button
          type="button"
          className="rounded-sm px-4 py-2 text-sm underline transition"
          style={{ color: 'var(--color-primary)' }}
          data-testid="cookie-privacy-settings-btn"
          onClick={openPrivacySettings}
        >
          Privacy settings
        </button>
        <button
          type="button"
          className="rounded-sm px-4 py-2 text-sm font-medium transition"
          style={{ color: 'var(--color-outline)' }}
          data-testid="cookie-decline-btn"
          onClick={declineAnalytics}
        >
          Decline
        </button>
        <button
          type="button"
          className="rounded-sm px-4 py-2 text-sm font-semibold text-white transition"
          style={{ backgroundColor: 'var(--color-primary)' }}
          data-testid="cookie-accept-btn"
          onClick={acceptAnalytics}
        >
          Allow analytics
        </button>
      </div>
    </div>
  )
}

// frontend/src/components/CookieConsentBanner.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAnalytics } from '../composables/useAnalytics'

const router = useRouter()
const { consent, dntEnabled, setAnalyticsConsent, trackEvent } = useAnalytics()

const visible = computed(() => consent.value === 'pending' && !dntEnabled.value)

function acceptAnalytics() {
  setAnalyticsConsent('granted')
  trackEvent('analytics_consent_updated', {
    consent: 'granted',
    source: 'cookie_banner',
  })
}

function declineAnalytics() {
  setAnalyticsConsent('denied')
}

function openPrivacySettings() {
  router.push('/settings/privacy')
}
</script>

<template>
  <div
    v-if="visible"
    class="fixed bottom-4 left-1/2 z-50 -translate-x-1/2 rounded bg-[var(--color-surface-container-low)] px-6 py-4 shadow-lg flex items-center gap-4 max-w-lg max-md:flex-col max-md:items-stretch"
    data-testid="cookie-consent-banner"
  >
    <div class="min-w-0">
      <strong class="block text-sm text-[var(--color-on-surface)]">Analytics preferences</strong>
      <p class="mt-1 text-sm text-[var(--color-on-surface-variant)]">
        Ace can use privacy-focused analytics and optional session recording to improve product quality.
      </p>
    </div>
    <div class="inline-flex items-center gap-2 flex-wrap justify-end max-md:justify-start">
      <button
        class="text-[var(--color-primary)] hover:text-[var(--color-primary)] underline text-sm px-4 py-2 rounded-sm transition"
        data-testid="cookie-privacy-settings-btn"
        @click="openPrivacySettings"
      >
        Privacy settings
      </button>
      <button
        class="rounded-sm px-4 py-2 text-sm font-medium text-[var(--color-outline)] hover:text-[var(--color-on-surface)] transition"
        data-testid="cookie-decline-btn"
        @click="declineAnalytics"
      >
        Decline
      </button>
      <button
        class="rounded-sm bg-[var(--color-primary)] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[var(--color-primary)]-hover"
        data-testid="cookie-accept-btn"
        @click="acceptAnalytics"
      >
        Allow analytics
      </button>
    </div>
  </div>
</template>
