// frontend/src/components/settings/CopilotConnectionPanel.tsx
import {
  AlertTriangle,
  Check,
  ClipboardCopy,
  ExternalLink,
  Github,
  Loader2,
  Unplug,
} from 'lucide-react'
import { useEffect, useState } from 'react'
import { useCopilotAuth } from '@/hooks/useCopilotAuth'

type CopilotConnectionPanelProps = {
  orgId: string
}

export function CopilotConnectionPanel({ orgId }: CopilotConnectionPanelProps) {
  const {
    isConnected,
    githubUsername,
    hasCopilot,
    error,
    deviceFlowActive,
    userCode,
    verificationUri,
    checkConnection,
    connect,
    cancelDeviceFlow,
    disconnect,
  } = useCopilotAuth()

  const [codeCopied, setCodeCopied] = useState(false)

  useEffect(() => {
    void checkConnection()
  }, [checkConnection])

  async function copyCode() {
    try {
      await navigator.clipboard.writeText(userCode)
      setCodeCopied(true)
      window.setTimeout(() => setCodeCopied(false), 2000)
    } catch {
      // fallback ignored
    }
  }

  function openGitHub() {
    window.open(verificationUri, '_blank')
  }

  return (
    <section
      className="rounded p-6"
      style={{ backgroundColor: 'var(--color-surface-container-low)' }}
      data-testid="copilot-connection-panel"
    >
      <div className="mb-4 flex items-center justify-between">
        <h2
          className="m-0 flex items-center gap-2 text-base font-semibold"
          style={{ color: 'var(--color-on-surface)' }}
        >
          <Github size={20} />
          GitHub Copilot
        </h2>
      </div>

      {error ? (
        <div
          className="mb-4 flex items-center gap-2 rounded-sm px-3 py-2.5 text-sm"
          style={{
            backgroundColor: 'rgba(239, 68, 68, 0.1)',
            border: '1px solid rgba(239, 68, 68, 0.25)',
            color: 'var(--color-error)',
          }}
        >
          <AlertTriangle size={14} />
          <span>{error}</span>
        </div>
      ) : null}

      {deviceFlowActive ? (
        <div className="flex flex-col items-center gap-5 py-6 text-center">
          <div className="flex flex-col gap-2">
            <h3 className="m-0 text-sm font-semibold" style={{ color: 'var(--color-on-surface)' }}>
              Your device code
            </h3>
            <p className="m-0 text-xs" style={{ color: 'var(--color-on-surface-variant)' }}>
              Copy the code below, then open GitHub to authorize.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <div
              data-testid="copilot-user-code"
              className="rounded px-4 py-2 font-mono text-2xl font-bold tracking-widest"
              style={{
                backgroundColor: 'var(--color-surface-container-high)',
                border: '1px solid rgba(255, 255, 255, 0.06)',
                color: 'var(--color-on-surface)',
              }}
            >
              {userCode}
            </div>
            <button
              type="button"
              className="flex h-10 w-10 cursor-pointer items-center justify-center rounded-sm transition"
              style={{
                backgroundColor: 'var(--color-surface-container-high)',
                border: '1px solid rgba(255, 255, 255, 0.06)',
                color: 'var(--color-on-surface-variant)',
              }}
              title="Copy code"
              onClick={() => void copyCode()}
            >
              {codeCopied ? (
                <Check size={14} style={{ color: 'var(--color-secondary)' }} />
              ) : (
                <ClipboardCopy size={14} />
              )}
            </button>
          </div>

          <button
            type="button"
            data-testid="copilot-open-github-btn"
            className="inline-flex cursor-pointer items-center gap-2 rounded-sm border-none px-4 py-2 text-sm font-semibold text-white transition"
            style={{ backgroundColor: 'var(--color-primary)' }}
            onClick={openGitHub}
          >
            <ExternalLink size={14} />
            Open GitHub
          </button>

          <div
            className="flex items-center gap-2 text-xs"
            style={{ color: 'var(--color-on-surface-variant)' }}
          >
            <Loader2 size={12} className="animate-spin" />
            Waiting for authorization...
          </div>

          <button
            type="button"
            data-testid="copilot-cancel-btn"
            className="inline-flex cursor-pointer items-center gap-1 border-none bg-transparent text-xs transition"
            style={{ color: 'var(--color-outline)' }}
            onClick={cancelDeviceFlow}
          >
            Cancel
          </button>
        </div>
      ) : null}

      {!deviceFlowActive && !isConnected ? (
        <div className="flex flex-col items-center gap-4 py-6 text-center">
          <p
            className="m-0 max-w-md text-sm"
            style={{ color: 'var(--color-on-surface-variant)' }}
          >
            Connect your GitHub account to use AI-assisted query writing powered by your Copilot
            subscription.
          </p>
          <button
            type="button"
            data-testid="copilot-connect-btn"
            className="inline-flex cursor-pointer items-center gap-2 rounded-sm border-none px-4 py-2 text-sm font-semibold text-white transition"
            style={{ backgroundColor: 'var(--color-primary)' }}
            onClick={() => void connect(orgId)}
          >
            <Github size={14} />
            Connect GitHub Copilot
          </button>
        </div>
      ) : null}

      {!deviceFlowActive && isConnected && hasCopilot ? (
        <div className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Github size={18} style={{ color: 'var(--color-on-surface-variant)' }} />
              <span className="text-sm font-medium" style={{ color: 'var(--color-on-surface)' }}>
                {githubUsername}
              </span>
              <span
                data-testid="copilot-active-badge"
                className="inline-flex items-center gap-1 rounded-sm px-2.5 py-0.5 text-xs font-semibold"
                style={{
                  backgroundColor: 'rgba(229, 160, 13, 0.1)',
                  border: '1px solid rgba(229, 160, 13, 0.2)',
                  color: 'var(--color-primary)',
                }}
              >
                Copilot Active
              </span>
            </div>
            <button
              type="button"
              data-testid="copilot-disconnect-btn"
              className="inline-flex cursor-pointer items-center gap-1 border-none bg-transparent text-xs transition"
              style={{ color: 'var(--color-outline)' }}
              onClick={() => void disconnect()}
            >
              <Unplug size={12} />
              Disconnect
            </button>
          </div>
        </div>
      ) : null}

      {!deviceFlowActive && isConnected && !hasCopilot ? (
        <div className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Github size={18} style={{ color: 'var(--color-on-surface-variant)' }} />
              <span className="text-sm font-medium" style={{ color: 'var(--color-on-surface)' }}>
                {githubUsername}
              </span>
            </div>
            <button
              type="button"
              data-testid="copilot-disconnect-btn"
              className="inline-flex cursor-pointer items-center gap-1 border-none bg-transparent text-xs transition"
              style={{ color: 'var(--color-outline)' }}
              onClick={() => void disconnect()}
            >
              <Unplug size={12} />
              Disconnect
            </button>
          </div>
          <div
            className="flex items-center gap-2 rounded-sm px-3 py-2.5 text-sm"
            style={{
              backgroundColor: 'rgba(249, 115, 22, 0.1)',
              border: '1px solid rgba(249, 115, 22, 0.2)',
              color: 'var(--color-tertiary)',
            }}
          >
            <AlertTriangle size={14} />
            <span>No active Copilot subscription detected.</span>
          </div>
        </div>
      ) : null}
    </section>
  )
}

// frontend/src/components/CopilotConnectionPanel.vue
<script setup lang="ts">
import {
  AlertTriangle,
  Check,
  ClipboardCopy,
  ExternalLink,
  Github,
  Loader2,
  Unplug,
} from 'lucide-vue-next'
import { onMounted, ref } from 'vue'
import { useCopilotAuth } from '../composables/useCopilotAuth'

const props = defineProps<{ orgId: string }>()

const {
  isConnected,
  githubUsername,
  hasCopilot,
  error,
  deviceFlowActive,
  userCode,
  verificationUri,
  checkConnection,
  connect,
  cancelDeviceFlow,
  disconnect,
} = useCopilotAuth()

const codeCopied = ref(false)

onMounted(() => {
  checkConnection()
})

async function copyCode() {
  try {
    await navigator.clipboard.writeText(userCode.value)
    codeCopied.value = true
    setTimeout(() => {
      codeCopied.value = false
    }, 2000)
  } catch {
    // fallback ignored
  }
}

function openGitHub() {
  window.open(verificationUri.value, '_blank')
}
</script>

<template>
  <section
    class="rounded p-6"
    :style="{ backgroundColor: 'var(--color-surface-container-low)' }"
  >
    <!-- Header -->
    <div class="flex justify-between items-center mb-4">
      <h2
        class="flex items-center gap-2 m-0 text-base font-semibold"
        :style="{ color: 'var(--color-on-surface)' }"
      >
        <Github :size="20" />
        GitHub Copilot
      </h2>
    </div>

    <!-- Error banner (shown alongside any state) -->
    <div
      v-if="error"
      class="flex items-center gap-2 rounded-sm px-3 py-2.5 text-sm mb-4"
      :style="{
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        border: '1px solid rgba(239, 68, 68, 0.25)',
        color: 'var(--color-error)',
      }"
    >
      <AlertTriangle :size="14" />
      <span>{{ error }}</span>
    </div>

    <!-- State 1: Device flow active -->
    <div
      v-if="deviceFlowActive"
      class="flex flex-col items-center gap-5 py-6 text-center"
    >
      <div class="flex flex-col gap-2">
        <h3
          class="text-sm font-semibold m-0"
          :style="{ color: 'var(--color-on-surface)' }"
        >
          Your device code
        </h3>
        <p
          class="text-xs m-0"
          :style="{ color: 'var(--color-on-surface-variant)' }"
        >
          Copy the code below, then open GitHub to authorize.
        </p>
      </div>

      <div class="flex items-center gap-2">
        <div
          data-testid="copilot-user-code"
          class="rounded px-4 py-2 font-mono text-2xl font-bold tracking-widest"
          :style="{
            backgroundColor: 'var(--color-surface-container-high)',
            border: '1px solid rgba(255, 255, 255, 0.06)',
            color: 'var(--color-on-surface)',
          }"
        >
          {{ userCode }}
        </div>
        <button
          class="flex items-center justify-center h-10 w-10 rounded-sm cursor-pointer transition"
          :style="{
            backgroundColor: 'var(--color-surface-container-high)',
            border: '1px solid rgba(255, 255, 255, 0.06)',
            color: 'var(--color-on-surface-variant)',
          }"
          title="Copy code"
          @click="copyCode"
        >
          <Check v-if="codeCopied" :size="14" :style="{ color: 'var(--color-secondary)' }" />
          <ClipboardCopy v-else :size="14" />
        </button>
      </div>

      <button
        data-testid="copilot-open-github-btn"
        class="inline-flex items-center gap-2 rounded-sm px-4 py-2 text-sm font-semibold text-white cursor-pointer border-none transition"
        :style="{ backgroundColor: 'var(--color-primary)' }"
        @click="openGitHub"
      >
        <ExternalLink :size="14" />
        Open GitHub
      </button>

      <div
        class="flex items-center gap-2 text-xs"
        :style="{ color: 'var(--color-on-surface-variant)' }"
      >
        <Loader2 :size="12" class="animate-spin" />
        Waiting for authorization...
      </div>

      <button
        data-testid="copilot-cancel-btn"
        class="inline-flex items-center gap-1 text-xs cursor-pointer border-none bg-transparent transition"
        :style="{ color: 'var(--color-outline)' }"
        @click="cancelDeviceFlow"
      >
        Cancel
      </button>
    </div>

    <!-- State 2: Not connected -->
    <div
      v-else-if="!isConnected"
      class="flex flex-col items-center gap-4 py-6 text-center"
    >
      <p
        class="text-sm m-0 max-w-md"
        :style="{ color: 'var(--color-on-surface-variant)' }"
      >
        Connect your GitHub account to use AI-assisted query writing powered by your Copilot subscription.
      </p>
      <button
        data-testid="copilot-connect-btn"
        class="inline-flex items-center gap-2 rounded-sm px-4 py-2 text-sm font-semibold text-white cursor-pointer border-none transition"
        :style="{ backgroundColor: 'var(--color-primary)' }"
        @click="connect(props.orgId)"
      >
        <Github :size="14" />
        Connect GitHub Copilot
      </button>
    </div>

    <!-- State 3: Connected with Copilot -->
    <div
      v-else-if="isConnected && hasCopilot"
      class="flex flex-col gap-4"
    >
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <Github :size="18" :style="{ color: 'var(--color-on-surface-variant)' }" />
          <span
            class="text-sm font-medium"
            :style="{ color: 'var(--color-on-surface)' }"
          >
            {{ githubUsername }}
          </span>
          <span
            data-testid="copilot-active-badge"
            class="inline-flex items-center gap-1 rounded-sm px-2.5 py-0.5 text-xs font-semibold"
            :style="{
              backgroundColor: 'rgba(229, 160, 13, 0.1)',
              border: '1px solid rgba(229, 160, 13, 0.2)',
              color: 'var(--color-primary)',
            }"
          >
            Copilot Active
          </span>
        </div>
        <button
          data-testid="copilot-disconnect-btn"
          class="inline-flex items-center gap-1 text-xs cursor-pointer border-none bg-transparent transition"
          :style="{ color: 'var(--color-outline)' }"
          @click="disconnect"
        >
          <Unplug :size="12" />
          Disconnect
        </button>
      </div>
    </div>

    <!-- State 4: Connected without Copilot -->
    <div
      v-else-if="isConnected && !hasCopilot"
      class="flex flex-col gap-4"
    >
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <Github :size="18" :style="{ color: 'var(--color-on-surface-variant)' }" />
          <span
            class="text-sm font-medium"
            :style="{ color: 'var(--color-on-surface)' }"
          >
            {{ githubUsername }}
          </span>
        </div>
        <button
          data-testid="copilot-disconnect-btn"
          class="inline-flex items-center gap-1 text-xs cursor-pointer border-none bg-transparent transition"
          :style="{ color: 'var(--color-outline)' }"
          @click="disconnect"
        >
          <Unplug :size="12" />
          Disconnect
        </button>
      </div>
      <div
        class="flex items-center gap-2 rounded-sm px-3 py-2.5 text-sm"
        :style="{
          backgroundColor: 'rgba(249, 115, 22, 0.1)',
          border: '1px solid rgba(249, 115, 22, 0.2)',
          color: 'var(--color-tertiary)',
        }"
      >
        <AlertTriangle :size="14" />
        <span>No active Copilot subscription detected.</span>
      </div>
    </div>
  </section>
</template>
