// frontend/src/components/DashboardSpecPreview.tsx
import {
  BarChart3,
  Check,
  ChevronDown,
  ChevronUp,
  ClipboardCopy,
  ExternalLink,
  Gauge,
  Hash,
  Loader2,
  type LucideIcon,
  PieChart,
  Table,
  TrendingUp,
} from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router'
import { queryDataSource } from '@/api/datasources'
import { useDatasources } from '@/hooks/useDatasources'
import { useOrganization } from '@/hooks/useOrganization'
import type { DashboardSpec, PanelType } from '@/utils/dashboardSpec'
import { saveDashboardSpec, validateDashboardSpec } from '@/utils/dashboardSpec'

type DryRunStatus = 'checking' | 'success' | 'empty' | 'error'

type DashboardSpecPreviewProps = {
  spec: DashboardSpec
  onSaved?: (dashboardId: string) => void
}

const DEMO_METRIC_NAMES = [
  'http_requests_total',
  'http_request_duration_seconds',
  'process_cpu_seconds',
  'process_resident_memory_bytes',
  'node_cpu_seconds',
  'node_memory_MemAvailable_bytes',
]

const panelTypeIcons: Record<PanelType, LucideIcon> = {
  line_chart: TrendingUp,
  bar_chart: BarChart3,
  stat: Hash,
  gauge: Gauge,
  table: Table,
  pie: PieChart,
}

function dryRunDotClass(status: DryRunStatus): string {
  switch (status) {
    case 'checking':
      return 'animate-pulse bg-[var(--color-outline)]'
    case 'success':
      return 'bg-[var(--color-secondary)]'
    case 'empty':
      return 'bg-[var(--color-tertiary)]'
    case 'error':
      return 'bg-[var(--color-error)]'
  }
}

export function DashboardSpecPreview({ spec, onSaved }: DashboardSpecPreviewProps) {
  const { currentOrgId } = useOrganization()
  const { data: datasources = [] } = useDatasources(currentOrgId)

  const [saving, setSaving] = useState(false)
  const [saveSuccess, setSaveSuccess] = useState(false)
  const [saveError, setSaveError] = useState<string | null>(null)
  const [savedDashboardId, setSavedDashboardId] = useState<string | null>(null)
  const [validationErrors, setValidationErrors] = useState<string[]>([])
  const [specExpanded, setSpecExpanded] = useState(false)
  const [specCopied, setSpecCopied] = useState(false)
  const [dryRunResults, setDryRunResults] = useState<Record<number, DryRunStatus>>({})

  const panelCount = spec.panels?.length ?? 0
  const knownDatasourceIds = useMemo(() => datasources.map((ds) => ds.id), [datasources])
  const isDemoSpec = useMemo(
    () =>
      Boolean(
        spec.panels?.some((panel) =>
          DEMO_METRIC_NAMES.some((metric) => panel.query.expr.includes(metric)),
        ),
      ),
    [spec.panels],
  )
  const maxGridRow = useMemo(() => {
    if (!spec.panels || spec.panels.length === 0) return 1
    return Math.max(
      ...spec.panels.map((panel) => (panel.position?.y ?? 0) + (panel.position?.h ?? 1)),
    )
  }, [spec.panels])
  const isSaved = savedDashboardId !== null
  const hasValidationErrors = validationErrors.length > 0

  useEffect(() => {
    setSavedDashboardId(null)
    setSaveSuccess(false)
    setSaveError(null)
    setValidationErrors([])

    if (!spec.panels || spec.panels.length === 0) {
      setDryRunResults({})
      return
    }

    let cancelled = false
    const initial: Record<number, DryRunStatus> = {}
    spec.panels.forEach((_, index) => {
      initial[index] = 'checking'
    })
    setDryRunResults(initial)

    const now = Math.floor(Date.now() / 1000)
    void Promise.allSettled(
      spec.panels.map(async (panel, index) => {
        try {
          const result = await queryDataSource(panel.datasource_id, {
            query: panel.query.expr,
            signal: panel.query.signal ?? 'metrics',
            start: now - 300,
            end: now,
            step: 15,
          })

          const hasData =
            result.status === 'success' && result.data?.result && result.data.result.length > 0

          if (!cancelled) {
            setDryRunResults((current) => ({
              ...current,
              [index]: hasData ? 'success' : 'empty',
            }))
          }
        } catch {
          if (!cancelled) {
            setDryRunResults((current) => ({
              ...current,
              [index]: 'error',
            }))
          }
        }
      }),
    )

    return () => {
      cancelled = true
    }
  }, [spec])

  async function handleSave() {
    const { valid, errors } = validateDashboardSpec(spec, knownDatasourceIds)
    if (!valid) {
      setValidationErrors(errors)
      return
    }
    setValidationErrors([])

    if (!currentOrgId) {
      setSaveError('No organization selected')
      return
    }

    setSaving(true)
    setSaveError(null)
    try {
      const id = await saveDashboardSpec(spec, currentOrgId)
      setSaveSuccess(true)
      window.setTimeout(() => {
        setSavedDashboardId(id)
        onSaved?.(id)
      }, 1000)
    } catch (cause) {
      setSaveError(cause instanceof Error ? cause.message : 'Failed to save dashboard')
    } finally {
      setSaving(false)
    }
  }

  async function copySpec() {
    try {
      await navigator.clipboard.writeText(JSON.stringify(spec, null, 2))
      setSpecCopied(true)
      window.setTimeout(() => setSpecCopied(false), 2000)
    } catch {
      // clipboard not available
    }
  }

  return (
    <section
      aria-label={`Dashboard preview: ${spec.title}, ${panelCount} panels`}
      className={`overflow-hidden rounded-lg border border-[color-mix(in_srgb,var(--color-outline-variant)_30%,transparent)] ${saving ? 'opacity-70' : ''}`}
    >
      <div className="flex items-center gap-2 px-3 py-2">
        <span className="truncate text-sm font-semibold text-[var(--color-on-surface)]">
          {spec.title}
        </span>
        <span className="shrink-0 text-xs text-[var(--color-outline)]">
          {panelCount} panel{panelCount !== 1 ? 's' : ''}
        </span>
      </div>

      {isDemoSpec && (
        <div className="px-3 pb-2">
          <span className="rounded bg-[var(--color-tertiary)]/10 px-2 py-1 text-xs text-[var(--color-tertiary)]">
            Demo dashboard — connect a real datasource to see your data
          </span>
        </div>
      )}

      <div className="px-3 pb-2">
        <ul
          className="m-0 grid list-none gap-1 p-0"
          style={{
            gridTemplateColumns: 'repeat(12, 1fr)',
            gridTemplateRows: `repeat(${maxGridRow}, 24px)`,
          }}
        >
          {spec.panels?.map((panel, index) => {
            const Icon = panelTypeIcons[panel.type] || TrendingUp
            const panelKey = `${panel.title}-${panel.type}-${panel.position?.x ?? 0}-${panel.position?.y ?? 0}-${panel.query.expr}`
            return (
              <li
                key={panelKey}
                aria-label={`${panel.title} (${panel.type})`}
                className="relative flex min-w-0 items-center gap-1 rounded bg-[var(--color-surface-container-low)] px-1.5 py-0.5"
                style={{
                  gridColumn: `${(panel.position?.x ?? 0) + 1} / span ${panel.position?.w ?? 4}`,
                  gridRow: `${(panel.position?.y ?? 0) + 1} / span ${panel.position?.h ?? 1}`,
                }}
              >
                <Icon size={10} className="shrink-0 text-[var(--color-outline)]" />
                <span className="truncate text-[10px] text-[var(--color-outline)]">
                  {panel.title}
                </span>
                {dryRunResults[index] && (
                  <span
                    className={`ml-auto h-2 w-2 shrink-0 rounded-full ${dryRunDotClass(dryRunResults[index]!)}`}
                  />
                )}
              </li>
            )
          })}
        </ul>
      </div>

      {hasValidationErrors && (
        <div className="px-3 pb-2">
          <ul className="m-0 list-inside list-disc rounded bg-[var(--color-error)]/10 px-3 py-2 text-xs text-[var(--color-error)]">
            {validationErrors.map((err) => (
              <li key={err}>{err}</li>
            ))}
          </ul>
        </div>
      )}

      {saveError && (
        <div className="px-3 pb-2" aria-live="polite">
          <span className="rounded bg-[var(--color-error)]/10 px-2 py-1 text-xs text-[var(--color-error)]">
            {saveError}
          </span>
        </div>
      )}

      <div className="flex items-center gap-3 px-3 pb-3" aria-live="polite">
        {isSaved ? (
          <>
            <span className="inline-flex items-center gap-1 text-sm font-semibold text-[var(--color-secondary)]">
              <Check size={14} />
              Dashboard saved
            </span>
            <Link
              to={`/app/dashboards/${savedDashboardId}`}
              className="inline-flex items-center gap-1 text-xs text-[var(--color-primary)] no-underline hover:underline"
            >
              <ExternalLink size={12} />
              Open dashboard
            </Link>
          </>
        ) : saveSuccess ? (
          <span className="inline-flex items-center gap-1 text-sm font-semibold text-[var(--color-secondary)]">
            <Check size={14} />
            Dashboard saved
          </span>
        ) : (
          <button
            type="button"
            className="inline-flex cursor-pointer items-center gap-1.5 rounded-sm border-none bg-[var(--color-primary)] px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
            disabled={saving || hasValidationErrors}
            data-testid="spec-preview-save-btn"
            onClick={() => void handleSave()}
          >
            {saving && <Loader2 size={14} className="animate-spin" />}
            {saving ? 'Saving...' : 'Save'}
          </button>
        )}

        <button
          type="button"
          className="ml-auto inline-flex cursor-pointer items-center gap-0.5 border-none bg-transparent text-xs text-[var(--color-outline)] hover:text-[var(--color-on-surface)]"
          aria-expanded={specExpanded}
          data-testid="spec-preview-toggle-spec"
          onClick={() => setSpecExpanded((current) => !current)}
        >
          View spec
          {specExpanded ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
        </button>
      </div>

      {specExpanded && (
        <div className="border-t border-[color-mix(in_srgb,var(--color-outline-variant)_30%,transparent)] px-3 py-2">
          <div className="mb-1 flex items-center justify-between">
            <span className="text-xs text-[var(--color-outline)]">Dashboard spec (JSON)</span>
            <button
              type="button"
              className="inline-flex cursor-pointer items-center gap-1 border-none bg-transparent text-xs text-[var(--color-outline)] hover:text-[var(--color-on-surface)]"
              data-testid="spec-preview-copy-btn"
              onClick={() => void copySpec()}
            >
              {specCopied ? (
                <Check size={12} className="text-[var(--color-secondary)]" />
              ) : (
                <ClipboardCopy size={12} />
              )}
              {specCopied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="m-0 max-h-48 overflow-x-auto overflow-y-auto rounded bg-[var(--color-surface-container-high)] p-2 text-[10px] text-[var(--color-on-surface-variant)]">
            {JSON.stringify(spec, null, 2)}
          </pre>
        </div>
      )}
    </section>
  )
}

// frontend/src/components/DashboardSpecPreview.vue
<script setup lang="ts">
import {
  BarChart3,
  Check,
  ChevronDown,
  ChevronUp,
  ClipboardCopy,
  ExternalLink,
  Gauge,
  Hash,
  Loader2,
  PieChart,
  Table,
  TrendingUp,
} from 'lucide-vue-next'
import { computed, onMounted, ref, type Component } from 'vue'
import { RouterLink } from 'vue-router'
import { queryDataSource } from '../api/datasources'
import { useDatasource } from '../composables/useDatasource'
import { useOrganization } from '../composables/useOrganization'
import type { DashboardSpec, PanelType } from '../utils/dashboardSpec'
import { saveDashboardSpec, validateDashboardSpec } from '../utils/dashboardSpec'

const props = defineProps<{
  spec: DashboardSpec
}>()

const emit = defineEmits<{
  saved: [dashboardId: string]
}>()

const { currentOrgId } = useOrganization()
const { datasources } = useDatasource()

// --- State ---

const saving = ref(false)
const saveSuccess = ref(false)
const saveError = ref<string | null>(null)
const savedDashboardId = ref<string | null>(null)
const validationErrors = ref<string[]>([])
const specExpanded = ref(false)
const specCopied = ref(false)

// Dry-run status per panel index
type DryRunStatus = 'checking' | 'success' | 'empty' | 'error'
const dryRunResults = ref<Record<number, DryRunStatus>>({})

// --- Computed ---

const panelCount = computed(() => props.spec.panels?.length ?? 0)

const knownDatasourceIds = computed(() => datasources.value.map((d) => d.id))

const DEMO_METRIC_NAMES = [
  'http_requests_total',
  'http_request_duration_seconds',
  'process_cpu_seconds',
  'process_resident_memory_bytes',
  'node_cpu_seconds',
  'node_memory_MemAvailable_bytes',
]

const isDemoSpec = computed(() => {
  if (!props.spec.panels) return false
  return props.spec.panels.some((panel) =>
    DEMO_METRIC_NAMES.some((metric) => panel.query.expr.includes(metric)),
  )
})

const panelTypeIcons: Record<PanelType, Component> = {
  line_chart: TrendingUp,
  bar_chart: BarChart3,
  stat: Hash,
  gauge: Gauge,
  table: Table,
  pie: PieChart,
}

/** Maximum row across all panels — used to size the grid height */
const maxGridRow = computed(() => {
  if (!props.spec.panels || props.spec.panels.length === 0) return 1
  return Math.max(...props.spec.panels.map((p) => (p.grid_pos?.y ?? 0) + (p.grid_pos?.h ?? 1)))
})

const isSaved = computed(() => savedDashboardId.value !== null)

const hasValidationErrors = computed(() => validationErrors.value.length > 0)

// --- Dry-run queries ---

async function runDryRuns() {
  if (!props.spec.panels || props.spec.panels.length === 0) return

  // Initialize all panels as checking
  const initial: Record<number, DryRunStatus> = {}
  props.spec.panels.forEach((_, i) => {
    initial[i] = 'checking'
  })
  dryRunResults.value = initial

  const now = Math.floor(Date.now() / 1000)

  const promises = props.spec.panels.map(async (panel, index) => {
    try {
      const result = await queryDataSource(panel.query.datasource_id, {
        query: panel.query.expr,
        signal: 'metrics',
        start: now - 300,
        end: now,
        step: 15,
      })

      const hasData =
        result.status === 'success' &&
        result.data?.result &&
        result.data.result.length > 0

      dryRunResults.value = {
        ...dryRunResults.value,
        [index]: hasData ? 'success' : 'empty',
      }
    } catch {
      dryRunResults.value = {
        ...dryRunResults.value,
        [index]: 'error',
      }
    }
  })

  await Promise.allSettled(promises)
}

onMounted(() => {
  runDryRuns()
})

// --- Save ---

async function handleSave() {
  // 1. Validate
  const { valid, errors } = validateDashboardSpec(props.spec, knownDatasourceIds.value)
  if (!valid) {
    validationErrors.value = errors
    return
  }
  validationErrors.value = []

  // 2. Save
  saving.value = true
  saveError.value = null
  try {
    const id = await saveDashboardSpec(props.spec, currentOrgId.value!)
    // Show success state in button for 1 second before transitioning to post-save
    saveSuccess.value = true
    setTimeout(() => {
      savedDashboardId.value = id
      emit('saved', id)
    }, 1000)
  } catch (e) {
    saveError.value = e instanceof Error ? e.message : 'Failed to save dashboard'
  } finally {
    saving.value = false
  }
}

// --- Spec viewer ---

async function copySpec() {
  try {
    await navigator.clipboard.writeText(JSON.stringify(props.spec, null, 2))
    specCopied.value = true
    setTimeout(() => {
      specCopied.value = false
    }, 2000)
  } catch {
    // clipboard not available
  }
}

// --- Helpers ---

function dryRunDotClass(status: DryRunStatus): string {
  switch (status) {
    case 'checking':
      return 'bg-text-muted animate-pulse'
    case 'success':
      return 'bg-[var(--color-secondary)]'
    case 'empty':
      return 'bg-[var(--color-tertiary)]'
    case 'error':
      return 'bg-[var(--color-error)]'
  }
}
</script>

<template>
  <div
    role="region"
    :aria-label="`Dashboard preview: ${spec.title}, ${panelCount} panels`"
    class="border  rounded-lg overflow-hidden"
    :class="{ 'opacity-70': saving }"
  >
    <!-- Header -->
    <div class="px-3 py-2 flex items-center gap-2">
      <span class="text-sm font-semibold text-[var(--color-on-surface)] truncate">{{ spec.title }}</span>
      <span class="text-xs text-[var(--color-outline)] shrink-0">{{ panelCount }} panel{{ panelCount !== 1 ? 's' : '' }}</span>
    </div>

    <!-- Demo badge -->
    <div v-if="isDemoSpec" class="px-3 pb-2">
      <span class="text-[var(--color-tertiary)] bg-[var(--color-tertiary)]/10 rounded px-2 py-1 text-xs">
        Demo dashboard — connect a real datasource to see your data
      </span>
    </div>

    <!-- Mini-panel grid -->
    <div
      class="px-3 pb-2"
    >
      <div
        role="list"
        class="grid gap-1"
        :style="{
          gridTemplateColumns: 'repeat(12, 1fr)',
          gridTemplateRows: `repeat(${maxGridRow}, 24px)`,
        }"
      >
        <div
          v-for="(panel, index) in spec.panels"
          :key="index"
          role="listitem"
          :aria-label="`${panel.title} (${panel.type})`"
          class="bg-[var(--color-surface-container-low)] rounded flex items-center gap-1 px-1.5 py-0.5 min-w-0 relative"
          :style="{
            gridColumn: `${(panel.grid_pos?.x ?? 0) + 1} / span ${panel.grid_pos?.w ?? 4}`,
            gridRow: `${(panel.grid_pos?.y ?? 0) + 1} / span ${panel.grid_pos?.h ?? 1}`,
          }"
        >
          <component
            :is="panelTypeIcons[panel.type] || TrendingUp"
            :size="10"
            class="text-[var(--color-outline)] shrink-0"
          />
          <span class="text-[10px] text-[var(--color-outline)] truncate">{{ panel.title }}</span>
          <!-- Dry-run status dot -->
          <span
            v-if="dryRunResults[index]"
            class="w-2 h-2 rounded-full shrink-0 ml-auto"
            :class="dryRunDotClass(dryRunResults[index]!)"
          />
        </div>
      </div>
    </div>

    <!-- Validation errors -->
    <div v-if="hasValidationErrors" class="px-3 pb-2">
      <ul class="text-[var(--color-error)] bg-[var(--color-error)]/10 rounded px-3 py-2 text-xs m-0 list-disc list-inside">
        <li v-for="(err, i) in validationErrors" :key="i">{{ err }}</li>
      </ul>
    </div>

    <!-- Save error -->
    <div v-if="saveError" class="px-3 pb-2" aria-live="polite">
      <span class="text-[var(--color-error)] bg-[var(--color-error)]/10 rounded px-2 py-1 text-xs">
        {{ saveError }}
      </span>
    </div>

    <!-- Actions -->
    <div class="px-3 pb-3 flex items-center gap-3" aria-live="polite">
      <!-- Post-save state -->
      <template v-if="isSaved">
        <span class="inline-flex items-center gap-1 text-[var(--color-secondary)] text-sm font-semibold">
          <Check :size="14" />
          Dashboard saved
        </span>
        <RouterLink
          :to="`/app/dashboards/${savedDashboardId}`"
          class="inline-flex items-center gap-1 text-xs text-[var(--color-primary)] no-underline hover:underline"
        >
          <ExternalLink :size="12" />
          Open dashboard
        </RouterLink>
      </template>

      <!-- Save success (intermediate, before post-save) -->
      <template v-else-if="saveSuccess">
        <span class="inline-flex items-center gap-1 text-[var(--color-secondary)] text-sm font-semibold">
          <Check :size="14" />
          Dashboard saved
        </span>
      </template>

      <!-- Save button -->
      <template v-else>
        <button
          class="inline-flex items-center gap-1.5 bg-[var(--color-primary)] text-white rounded-sm px-4 py-2 text-sm font-semibold border-none cursor-pointer transition hover:bg-[var(--color-primary)]-hover disabled:opacity-50 disabled:cursor-not-allowed"
          :disabled="saving || hasValidationErrors"
          data-testid="spec-preview-save-btn"
          @click="handleSave"
        >
          <Loader2 v-if="saving" :size="14" class="animate-spin" />
          {{ saving ? 'Saving...' : 'Save' }}
        </button>
      </template>

      <!-- View spec toggle -->
      <button
        class="text-xs text-[var(--color-outline)] cursor-pointer border-none bg-transparent hover:text-[var(--color-on-surface)] ml-auto inline-flex items-center gap-0.5"
        :aria-expanded="specExpanded"
        data-testid="spec-preview-toggle-spec"
        @click="specExpanded = !specExpanded"
      >
        View spec
        <ChevronUp v-if="specExpanded" :size="12" />
        <ChevronDown v-else :size="12" />
      </button>
    </div>

    <!-- Collapsible JSON spec -->
    <div v-if="specExpanded" class="border-t  px-3 py-2">
      <div class="flex items-center justify-between mb-1">
        <span class="text-xs text-[var(--color-outline)]">Dashboard spec (JSON)</span>
        <button
          class="inline-flex items-center gap-1 text-xs text-[var(--color-outline)] cursor-pointer border-none bg-transparent hover:text-[var(--color-on-surface)]"
          data-testid="spec-preview-copy-btn"
          @click="copySpec"
        >
          <Check v-if="specCopied" :size="12" class="text-[var(--color-secondary)]" />
          <ClipboardCopy v-else :size="12" />
          {{ specCopied ? 'Copied' : 'Copy' }}
        </button>
      </div>
      <pre class="text-[10px] text-[var(--color-on-surface-variant)] bg-[var(--color-surface-container-high)] rounded p-2 overflow-x-auto m-0 max-h-48 overflow-y-auto">{{ JSON.stringify(spec, null, 2) }}</pre>
    </div>
  </div>
</template>
