// frontend/src/components/LogQLQueryBuilder.tsx
import { Code, Layers, Plus, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { fetchDataSourceLabelValues } from '@/api/datasources'
import { MonacoQueryEditor } from '@/components/MonacoQueryEditor'

const LOGQL_LABEL_OPERATORS = [
  { value: '=', label: '=' },
  { value: '!=', label: '!=' },
  { value: '=~', label: '=~' },
  { value: '!~', label: '!~' },
] as const

const LOGQL_LINE_FILTER_OPERATORS = [
  { value: '|=', label: '|=' },
  { value: '!=', label: '!=' },
  { value: '|~', label: '|~' },
  { value: '!~', label: '!~' },
] as const

const LOGSQL_FIELD_OPERATORS = [
  { value: 'eq', label: ':=' },
  { value: 'neq', label: 'NOT :=' },
  { value: 'regex', label: ':~' },
  { value: 'nregex', label: 'NOT :~' },
] as const

const LOGSQL_TEXT_OPERATORS = [
  { value: 'contains', label: 'Contains' },
  { value: 'not_contains', label: 'Not contains' },
  { value: 'regex', label: 'Regex' },
  { value: 'not_regex', label: 'Not regex' },
] as const

type QueryLanguage = 'logql' | 'logsql'

type LabelFilter = {
  id: string
  label: string
  operator: string
  value: string
}

type LogQLQueryBuilderProps = {
  value: string
  onChange: (value: string) => void
  onSubmit?: () => void
  indexedLabels: string[]
  datasourceId: string
  queryLanguage?: QueryLanguage
  disabled?: boolean
  editorHeight?: number
  placeholder?: string
}

let filterIdCounter = 0

function generateFilterId() {
  filterIdCounter += 1
  return `logql-filter-${filterIdCounter}`
}

function quoteLogsQLField(value: string) {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function escapeLogQLValue(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function normalizeFieldOperator(
  value: string,
  operators: readonly { value: string; label: string }[],
) {
  if (operators.some(operator => operator.value === value)) {
    return value
  }
  return operators[0].value
}

function normalizeTextOperator(
  value: string,
  operators: readonly { value: string; label: string }[],
) {
  if (operators.some(operator => operator.value === value)) {
    return value
  }
  return operators[0].value
}

function buildLogsQLFieldFilter(filter: LabelFilter) {
  const fieldName = quoteLogsQLField(filter.label)
  const escapedValue = escapeLogQLValue(filter.value.trim())
  const operator = filter.operator

  if (operator === 'neq') {
    return `NOT ${fieldName}:="${escapedValue}"`
  }
  if (operator === 'regex') {
    return `${fieldName}:~"${escapedValue}"`
  }
  if (operator === 'nregex') {
    return `NOT ${fieldName}:~"${escapedValue}"`
  }
  return `${fieldName}:="${escapedValue}"`
}

function buildLogsQLTextFilter(lineFilterOperator: string, lineFilterValue: string) {
  const value = lineFilterValue.trim()
  if (!value) {
    return ''
  }

  const escapedValue = escapeLogQLValue(value)
  const operator = lineFilterOperator

  if (operator === 'not_contains') {
    return `NOT "${escapedValue}"`
  }
  if (operator === 'regex') {
    return `_msg:~"${escapedValue}"`
  }
  if (operator === 'not_regex') {
    return `NOT _msg:~"${escapedValue}"`
  }
  return `"${escapedValue}"`
}

function buildLogQLQuery(
  labelFilters: LabelFilter[],
  lineFilterOperator: string,
  lineFilterValue: string,
  fieldOperators: readonly { value: string; label: string }[],
  textOperators: readonly { value: string; label: string }[],
) {
  const selectorFilters = labelFilters
    .filter(filter => filter.label && filter.value.trim())
    .map(
      filter =>
        `${filter.label}${normalizeFieldOperator(filter.operator, fieldOperators)}"${escapeLogQLValue(filter.value.trim())}"`,
    )

  const hasLineFilter = lineFilterValue.trim().length > 0
  if (selectorFilters.length === 0 && !hasLineFilter) {
    return ''
  }

  const selector = selectorFilters.length > 0 ? `{${selectorFilters.join(',')}}` : '{}'
  if (!hasLineFilter) {
    return selector
  }

  return `${selector} ${normalizeTextOperator(lineFilterOperator, textOperators)} "${escapeLogQLValue(lineFilterValue.trim())}"`
}

function buildLogsSQLQuery(
  labelFilters: LabelFilter[],
  lineFilterOperator: string,
  lineFilterValue: string,
) {
  const filters = labelFilters
    .filter(filter => filter.label && filter.value.trim())
    .map(buildLogsQLFieldFilter)

  const textFilter = buildLogsQLTextFilter(lineFilterOperator, lineFilterValue)
  if (filters.length === 0 && !textFilter) {
    return '*'
  }

  const queryParts = ['*', ...filters]
  if (textFilter) {
    queryParts.push(textFilter)
  }

  return queryParts.join(' ')
}

export function LogQLQueryBuilder({
  value,
  onChange,
  onSubmit,
  indexedLabels,
  datasourceId,
  queryLanguage = 'logql',
  disabled = false,
  editorHeight = 130,
  placeholder = '{job=~".+"} |= "error"',
}: LogQLQueryBuilderProps) {
  const isLogsQL = queryLanguage === 'logsql'
  const fieldOperators = isLogsQL ? LOGSQL_FIELD_OPERATORS : LOGQL_LABEL_OPERATORS
  const textOperators = isLogsQL ? LOGSQL_TEXT_OPERATORS : LOGQL_LINE_FILTER_OPERATORS

  const [mode, setMode] = useState<'builder' | 'code'>('builder')
  const [codeQuery, setCodeQuery] = useState(value)
  const [labelFilters, setLabelFilters] = useState<LabelFilter[]>([])
  const [lineFilterOperator, setLineFilterOperator] = useState<string>(textOperators[0].value)
  const [lineFilterValue, setLineFilterValue] = useState('')
  const [labelValuesCache, setLabelValuesCache] = useState<Map<string, string[]>>(new Map())
  const [loadingLabelValues, setLoadingLabelValues] = useState<string | null>(null)
  const isEmittingRef = useRef(false)

  const generatedQuery = useMemo(() => {
    if (isLogsQL) {
      return buildLogsSQLQuery(labelFilters, lineFilterOperator, lineFilterValue)
    }
    return buildLogQLQuery(
      labelFilters,
      lineFilterOperator,
      lineFilterValue,
      fieldOperators,
      textOperators,
    )
  }, [fieldOperators, isLogsQL, labelFilters, lineFilterOperator, lineFilterValue, textOperators])

  const builderAvailable = useMemo(() => {
    if (!codeQuery) return true
    if (mode === 'builder' && generatedQuery) return true
    if (codeQuery === generatedQuery) return true
    return false
  }, [codeQuery, generatedQuery, mode])

  const activeQuery = mode === 'builder' ? generatedQuery : codeQuery

  const generatedQueryLabel = isLogsQL ? 'Generated LogsQL' : 'Generated LogQL'
  const codeEditorLabel = isLogsQL ? 'LogsQL Query' : 'LogQL Query'
  const lineFilterLabel = isLogsQL ? 'Message Filter (Optional)' : 'Line Filter (Optional)'
  const lineFilterPlaceholder = isLogsQL
    ? 'Phrase or regex for _msg field'
    : 'Contains text, regex, or exact match'

  const loadLabelValues = useCallback(async (labelName: string) => {
    if (!datasourceId || !labelName) return []

    let cached: string[] | undefined
    setLabelValuesCache(prev => {
      cached = prev.get(labelName)
      return prev
    })
    if (cached) {
      return cached
    }

    setLoadingLabelValues(labelName)
    try {
      const values = await fetchDataSourceLabelValues(datasourceId, labelName)
      setLabelValuesCache(prev => {
        const next = new Map(prev)
        next.set(labelName, values)
        return next
      })
      return values
    } catch (error) {
      console.error(`Failed to load label values for ${labelName}:`, error)
      setLabelValuesCache(prev => {
        const next = new Map(prev)
        next.set(labelName, [])
        return next
      })
      return []
    } finally {
      setLoadingLabelValues(current => (current === labelName ? null : current))
    }
  }, [datasourceId])

  function addLabelFilter() {
    setLabelFilters(prev => [
      ...prev,
      {
        id: generateFilterId(),
        label: '',
        operator: fieldOperators[0].value,
        value: '',
      },
    ])
  }

  function removeLabelFilter(id: string) {
    setLabelFilters(prev => prev.filter(filter => filter.id !== id))
  }

  function updateLabelFilter(id: string, updates: Partial<LabelFilter>) {
    setLabelFilters(prev =>
      prev.map(filter => (filter.id === id ? { ...filter, ...updates } : filter)),
    )
  }

  async function handleLabelChange(filter: LabelFilter, newLabel: string) {
    updateLabelFilter(filter.id, { label: newLabel, value: '' })
    if (!newLabel) return
    await loadLabelValues(newLabel)
  }

  function getLabelValues(labelName: string) {
    return labelValuesCache.get(labelName) || []
  }

  useEffect(() => {
    setLabelValuesCache(new Map())
    setLoadingLabelValues(null)
  }, [datasourceId])

  useEffect(() => {
    setLineFilterOperator(textOperators[0].value)
    setLabelFilters(prev =>
      prev.map(filter => ({
        ...filter,
        operator: normalizeFieldOperator(filter.operator, fieldOperators),
      })),
    )
  }, [fieldOperators, textOperators])

  useEffect(() => {
    if (isEmittingRef.current) return
    if (value === activeQuery) return

    setCodeQuery(value)
    if (value !== generatedQuery) {
      setMode('code')
    }
  }, [value, activeQuery, generatedQuery])

  useEffect(() => {
    isEmittingRef.current = true
    onChange(activeQuery)
    queueMicrotask(() => {
      isEmittingRef.current = false
    })
  }, [activeQuery, onChange])

  return (
    <div
      className={`flex flex-col gap-4 ${disabled ? 'pointer-events-none opacity-60' : ''}`}
      data-testid="logql-query-builder"
    >
      <div className="flex w-fit rounded-sm bg-[var(--color-surface-container-high)] p-1">
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-sm border-none bg-transparent px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:text-[var(--color-on-surface)] disabled:cursor-not-allowed disabled:opacity-40 ${
            mode === 'builder'
              ? 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm'
              : ''
          }`}
          data-testid="logql-builder-mode-btn"
          disabled={disabled || !builderAvailable}
          title={!builderAvailable ? 'Query cannot be edited in builder mode' : ''}
          onClick={() => setMode('builder')}
        >
          <Layers size={14} />
          <span>Builder</span>
        </button>
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-sm border-none bg-transparent px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:text-[var(--color-on-surface)] disabled:cursor-not-allowed disabled:opacity-40 ${
            mode === 'code'
              ? 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm'
              : ''
          }`}
          data-testid="logql-code-mode-btn"
          disabled={disabled}
          onClick={() => setMode('code')}
        >
          <Code size={14} />
          <span>Code</span>
        </button>
      </div>

      {mode === 'builder' ? (
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-[var(--color-on-surface)]">
                Stream Filters
              </label>
              <button
                type="button"
                className="flex items-center gap-1.5 rounded-sm px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:bg-[var(--color-surface-container-high)] hover:enabled:text-[var(--color-on-surface)]"
                data-testid="logql-add-filter-btn"
                disabled={disabled}
                onClick={addLabelFilter}
              >
                <Plus size={14} />
                <span>Add Filter</span>
              </button>
            </div>

            {labelFilters.length === 0 ? (
              <div className="rounded-sm bg-[var(--color-surface-container-high)] p-4 text-center text-sm text-[var(--color-outline)]">
                No filters yet. Add a field filter to build your selector.
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                {labelFilters.map(filter => (
                  <div key={filter.id} className="flex items-center gap-2">
                    <select
                      className="min-w-0 flex-1 cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
                      value={filter.label}
                      disabled={disabled}
                      onChange={event => void handleLabelChange(filter, event.target.value)}
                    >
                      <option value="">Indexed field</option>
                      {indexedLabels.map(label => (
                        <option key={label} value={label}>
                          {label}
                        </option>
                      ))}
                    </select>

                    <select
                      className="w-[120px] flex-none cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 font-mono text-sm text-[var(--color-on-surface-variant)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
                      value={filter.operator}
                      disabled={disabled}
                      onChange={event =>
                        updateLabelFilter(filter.id, { operator: event.target.value })
                      }
                    >
                      {fieldOperators.map(operator => (
                        <option key={operator.value} value={operator.value}>
                          {operator.label}
                        </option>
                      ))}
                    </select>

                    {getLabelValues(filter.label).length > 0 ? (
                      <select
                        className="min-w-0 flex-1 cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
                        value={filter.value}
                        disabled={disabled || loadingLabelValues === filter.label}
                        onChange={event =>
                          updateLabelFilter(filter.id, { value: event.target.value })
                        }
                      >
                        <option value="">Field value</option>
                        {getLabelValues(filter.label).map(labelValue => (
                          <option key={labelValue} value={labelValue}>
                            {labelValue}
                          </option>
                        ))}
                      </select>
                    ) : (
                      <input
                        className="min-w-0 flex-1 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
                        type="text"
                        placeholder="Field value"
                        value={filter.value}
                        disabled={disabled}
                        onChange={event =>
                          updateLabelFilter(filter.id, { value: event.target.value })
                        }
                      />
                    )}

                    <button
                      type="button"
                      className="flex h-7 w-7 items-center justify-center rounded border-none bg-transparent text-[var(--color-outline)] transition-all duration-200 hover:enabled:bg-[var(--color-error)]/10 hover:enabled:text-[var(--color-error)]"
                      disabled={disabled}
                      onClick={() => removeLabelFilter(filter.id)}
                    >
                      <X size={14} />
                    </button>
                  </div>
                ))}

                {loadingLabelValues ? (
                  <span className="text-xs text-[var(--color-outline)]">
                    Loading indexed values...
                  </span>
                ) : null}
              </div>
            )}
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-[var(--color-on-surface)]">
              {lineFilterLabel}
            </label>
            <div className="flex items-center gap-2">
              <select
                data-testid="logql-line-filter-operator-select"
                className="w-[120px] flex-none cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 font-mono text-sm text-[var(--color-on-surface-variant)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
                value={lineFilterOperator}
                disabled={disabled}
                onChange={event => setLineFilterOperator(event.target.value)}
              >
                {textOperators.map(operator => (
                  <option key={operator.value} value={operator.value}>
                    {operator.label}
                  </option>
                ))}
              </select>
              <input
                data-testid="logql-line-filter-value-input"
                className="min-w-0 flex-1 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
                type="text"
                placeholder={lineFilterPlaceholder}
                value={lineFilterValue}
                disabled={disabled}
                onChange={event => setLineFilterValue(event.target.value)}
              />
            </div>
          </div>

          <div className="mt-2 flex flex-col gap-2 pt-4">
            <label className="text-sm font-medium text-[var(--color-on-surface)]">
              {generatedQueryLabel}
            </label>
            <div className="min-h-[48px] rounded-sm bg-[var(--color-surface-container-high)] px-4 py-3">
              {generatedQuery ? (
                <code className="break-all font-mono text-sm text-[var(--color-primary)]">
                  {generatedQuery}
                </code>
              ) : (
                <span className="text-sm text-[var(--color-outline)]">
                  Add a field/value filter to generate a query
                </span>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <label className="text-sm font-medium text-[var(--color-on-surface)]">
            {codeEditorLabel}
          </label>
          <MonacoQueryEditor
            value={codeQuery}
            onChange={setCodeQuery}
            onSubmit={onSubmit}
            disabled={disabled}
            height={editorHeight}
            placeholder={placeholder}
            language={queryLanguage}
          />
        </div>
      )}
    </div>
  )
}

// frontend/src/components/LogQLQueryBuilder.vue
<script setup lang="ts">
import { Code, Layers, Plus, X } from 'lucide-vue-next'
import { computed, nextTick, ref, watch } from 'vue'
import { fetchDataSourceLabelValues } from '../api/datasources'
import MonacoQueryEditor from './MonacoQueryEditor.vue'

const LOGQL_LABEL_OPERATORS = [
  { value: '=', label: '=' },
  { value: '!=', label: '!=' },
  { value: '=~', label: '=~' },
  { value: '!~', label: '!~' },
] as const

const LOGQL_LINE_FILTER_OPERATORS = [
  { value: '|=', label: '|=' },
  { value: '!=', label: '!=' },
  { value: '|~', label: '|~' },
  { value: '!~', label: '!~' },
] as const

const LOGSQL_FIELD_OPERATORS = [
  { value: 'eq', label: ':=' },
  { value: 'neq', label: 'NOT :=' },
  { value: 'regex', label: ':~' },
  { value: 'nregex', label: 'NOT :~' },
] as const

const LOGSQL_TEXT_OPERATORS = [
  { value: 'contains', label: 'Contains' },
  { value: 'not_contains', label: 'Not contains' },
  { value: 'regex', label: 'Regex' },
  { value: 'not_regex', label: 'Not regex' },
] as const

type QueryLanguage = 'logql' | 'logsql'

interface LabelFilter {
  id: string
  label: string
  operator: string
  value: string
}

const props = withDefaults(
  defineProps<{
    modelValue: string
    indexedLabels: string[]
    datasourceId: string
    queryLanguage?: QueryLanguage
    disabled?: boolean
    editorHeight?: number
    placeholder?: string
  }>(),
  {
    queryLanguage: 'logql',
    disabled: false,
    editorHeight: 130,
    placeholder: '{job=~".+"} |= "error"',
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string]
  submit: []
}>()

const mode = ref<'builder' | 'code'>('builder')
const codeQuery = ref(props.modelValue)
const labelFilters = ref<LabelFilter[]>([])
const lineFilterOperator = ref<string>(props.queryLanguage === 'logsql' ? 'contains' : '|=')
const lineFilterValue = ref('')
const labelValuesCache = ref<Map<string, string[]>>(new Map())
const loadingLabelValues = ref<string | null>(null)
const isEmitting = ref(false)

let filterIdCounter = 0

function generateFilterId() {
  filterIdCounter += 1
  return `logql-filter-${filterIdCounter}`
}

const isLogsQL = computed(() => props.queryLanguage === 'logsql')

const fieldOperators = computed(() => {
  return isLogsQL.value ? LOGSQL_FIELD_OPERATORS : LOGQL_LABEL_OPERATORS
})

const textOperators = computed(() => {
  return isLogsQL.value ? LOGSQL_TEXT_OPERATORS : LOGQL_LINE_FILTER_OPERATORS
})

const generatedQueryLabel = computed(() =>
  isLogsQL.value ? 'Generated LogsQL' : 'Generated LogQL',
)
const codeEditorLabel = computed(() => (isLogsQL.value ? 'LogsQL Query' : 'LogQL Query'))
const lineFilterLabel = computed(() =>
  isLogsQL.value ? 'Message Filter (Optional)' : 'Line Filter (Optional)',
)
const lineFilterPlaceholder = computed(() => {
  return isLogsQL.value ? 'Phrase or regex for _msg field' : 'Contains text, regex, or exact match'
})

function normalizeFieldOperator(value: string) {
  if (fieldOperators.value.some((operator) => operator.value === value)) {
    return value
  }
  return fieldOperators.value[0].value
}

function normalizeTextOperator(value: string) {
  if (textOperators.value.some((operator) => operator.value === value)) {
    return value
  }
  return textOperators.value[0].value
}

function quoteLogsQLField(value: string) {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function escapeLogQLValue(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function buildLogsQLFieldFilter(filter: LabelFilter) {
  const fieldName = quoteLogsQLField(filter.label)
  const escapedValue = escapeLogQLValue(filter.value.trim())
  const operator = normalizeFieldOperator(filter.operator)

  if (operator === 'neq') {
    return `NOT ${fieldName}:="${escapedValue}"`
  }
  if (operator === 'regex') {
    return `${fieldName}:~"${escapedValue}"`
  }
  if (operator === 'nregex') {
    return `NOT ${fieldName}:~"${escapedValue}"`
  }
  return `${fieldName}:="${escapedValue}"`
}

function buildLogsQLTextFilter() {
  const value = lineFilterValue.value.trim()
  if (!value) {
    return ''
  }

  const escapedValue = escapeLogQLValue(value)
  const operator = normalizeTextOperator(lineFilterOperator.value)

  if (operator === 'not_contains') {
    return `NOT "${escapedValue}"`
  }
  if (operator === 'regex') {
    return `_msg:~"${escapedValue}"`
  }
  if (operator === 'not_regex') {
    return `NOT _msg:~"${escapedValue}"`
  }
  return `"${escapedValue}"`
}

const generatedQuery = computed(() => {
  if (isLogsQL.value) {
    const filters = labelFilters.value
      .filter((filter) => filter.label && filter.value.trim())
      .map(buildLogsQLFieldFilter)

    const textFilter = buildLogsQLTextFilter()
    if (filters.length === 0 && !textFilter) {
      return '*'
    }

    const queryParts = ['*', ...filters]
    if (textFilter) {
      queryParts.push(textFilter)
    }

    return queryParts.join(' ')
  }

  const selectorFilters = labelFilters.value
    .filter((filter) => filter.label && filter.value.trim())
    .map(
      (filter) =>
        `${filter.label}${normalizeFieldOperator(filter.operator)}"${escapeLogQLValue(filter.value.trim())}"`,
    )

  const hasLineFilter = lineFilterValue.value.trim().length > 0
  if (selectorFilters.length === 0 && !hasLineFilter) {
    return ''
  }

  const selector = selectorFilters.length > 0 ? `{${selectorFilters.join(',')}}` : '{}'
  if (!hasLineFilter) {
    return selector
  }

  return `${selector} ${normalizeTextOperator(lineFilterOperator.value)} "${escapeLogQLValue(lineFilterValue.value.trim())}"`
})

const builderAvailable = computed(() => {
  if (!codeQuery.value) return true
  if (mode.value === 'builder' && generatedQuery.value) return true
  if (codeQuery.value === generatedQuery.value) return true
  return false
})

const activeQuery = computed(() => {
  return mode.value === 'builder' ? generatedQuery.value : codeQuery.value
})

function addLabelFilter() {
  labelFilters.value.push({
    id: generateFilterId(),
    label: '',
    operator: fieldOperators.value[0].value,
    value: '',
  })
}

function removeLabelFilter(id: string) {
  labelFilters.value = labelFilters.value.filter((filter) => filter.id !== id)
}

function updateLabelFilter(id: string, updates: Partial<LabelFilter>) {
  const filter = labelFilters.value.find((current) => current.id === id)
  if (!filter) return
  Object.assign(filter, updates)
}

async function loadLabelValues(labelName: string) {
  if (!props.datasourceId || !labelName) return []

  if (labelValuesCache.value.has(labelName)) {
    return labelValuesCache.value.get(labelName) || []
  }

  loadingLabelValues.value = labelName
  try {
    const values = await fetchDataSourceLabelValues(props.datasourceId, labelName)
    labelValuesCache.value.set(labelName, values)
    return values
  } catch (error) {
    console.error(`Failed to load label values for ${labelName}:`, error)
    labelValuesCache.value.set(labelName, [])
    return []
  } finally {
    if (loadingLabelValues.value === labelName) {
      loadingLabelValues.value = null
    }
  }
}

async function handleLabelChange(filter: LabelFilter, newLabel: string) {
  updateLabelFilter(filter.id, { label: newLabel, value: '' })
  if (!newLabel) return
  await loadLabelValues(newLabel)
}

function getLabelValues(labelName: string) {
  return labelValuesCache.value.get(labelName) || []
}

function emitSubmit() {
  emit('submit')
}

watch(
  () => props.datasourceId,
  () => {
    labelValuesCache.value = new Map()
    loadingLabelValues.value = null
  },
)

watch(
  () => props.queryLanguage,
  () => {
    lineFilterOperator.value = textOperators.value[0].value
    labelFilters.value = labelFilters.value.map((filter) => ({
      ...filter,
      operator: normalizeFieldOperator(filter.operator),
    }))
  },
)

watch(
  () => props.modelValue,
  (newValue) => {
    if (isEmitting.value) return
    if (newValue === activeQuery.value) return

    codeQuery.value = newValue
    if (newValue !== generatedQuery.value) {
      mode.value = 'code'
    }
  },
)

watch(mode, (newMode, oldMode) => {
  if (newMode === 'code' && oldMode === 'builder' && generatedQuery.value) {
    codeQuery.value = generatedQuery.value
  }
})

watch(activeQuery, (newValue) => {
  isEmitting.value = true
  emit('update:modelValue', newValue)
  nextTick(() => {
    isEmitting.value = false
  })
})
</script>

<template>
  <div class="flex flex-col gap-4" :class="{ 'opacity-60 pointer-events-none': props.disabled }">
    <div class="flex rounded-sm bg-[var(--color-surface-container-high)] p-1 w-fit">
      <button
        type="button"
        class="flex items-center gap-1.5 px-3 py-1.5 bg-transparent border-none rounded-sm text-xs font-medium text-[var(--color-on-surface-variant)] cursor-pointer transition-all duration-200 disabled:opacity-40 disabled:cursor-not-allowed hover:enabled:text-[var(--color-on-surface)]"
        :class="{ 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm': mode === 'builder' }"
        data-testid="logql-builder-mode-btn"
        :disabled="props.disabled || !builderAvailable"
        :title="!builderAvailable ? 'Query cannot be edited in builder mode' : ''"
        @click="mode = 'builder'"
      >
        <Layers :size="14" />
        <span>Builder</span>
      </button>
      <button
        type="button"
        class="flex items-center gap-1.5 px-3 py-1.5 bg-transparent border-none rounded-sm text-xs font-medium text-[var(--color-on-surface-variant)] cursor-pointer transition-all duration-200 disabled:opacity-40 disabled:cursor-not-allowed hover:enabled:text-[var(--color-on-surface)]"
        :class="{ 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm': mode === 'code' }"
        data-testid="logql-code-mode-btn"
        :disabled="props.disabled"
        @click="mode = 'code'"
      >
        <Code :size="14" />
        <span>Code</span>
      </button>
    </div>

    <div v-if="mode === 'builder'" class="flex flex-col gap-4">
      <div class="flex flex-col gap-2">
        <div class="flex justify-between items-center">
          <label class="text-sm font-medium text-[var(--color-on-surface)]">Stream Filters</label>
          <button
            type="button"
            class="flex items-center gap-1.5 px-3 py-1.5 rounded-sm text-xs font-medium text-[var(--color-on-surface-variant)] cursor-pointer transition-all duration-200 hover:enabled:bg-[var(--color-surface-container-high)] hover:enabled:text-[var(--color-on-surface)]"
            data-testid="logql-add-filter-btn"
            :disabled="props.disabled"
            @click="addLabelFilter"
          >
            <Plus :size="14" />
            <span>Add Filter</span>
          </button>
        </div>

        <div v-if="labelFilters.length === 0" class="p-4 text-center text-[var(--color-outline)] text-sm bg-[var(--color-surface-container-high)] rounded-sm">
          No filters yet. Add a field filter to build your selector.
        </div>

        <div v-else class="flex flex-col gap-2">
          <div v-for="filter in labelFilters" :key="filter.id" class="flex items-center gap-2">
            <select
              class="flex-1 min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :value="filter.label"
              :disabled="props.disabled"
              @change="handleLabelChange(filter, ($event.target as HTMLSelectElement).value)"
            >
              <option value="">Indexed field</option>
              <option v-for="label in props.indexedLabels" :key="label" :value="label">
                {{ label }}
              </option>
            </select>

            <select
              class="w-[120px] flex-none rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm font-mono text-[var(--color-on-surface-variant)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :value="filter.operator"
              :disabled="props.disabled"
              @change="updateLabelFilter(filter.id, { operator: ($event.target as HTMLSelectElement).value })"
            >
              <option v-for="operator in fieldOperators" :key="operator.value" :value="operator.value">
                {{ operator.label }}
              </option>
            </select>

            <select
              v-if="getLabelValues(filter.label).length > 0"
              class="flex-1 min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :value="filter.value"
              :disabled="props.disabled || loadingLabelValues === filter.label"
              @change="updateLabelFilter(filter.id, { value: ($event.target as HTMLSelectElement).value })"
            >
              <option value="">Field value</option>
              <option v-for="value in getLabelValues(filter.label)" :key="value" :value="value">
                {{ value }}
              </option>
            </select>
            <input
              v-else
              class="flex-1 min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              type="text"
              placeholder="Field value"
              :value="filter.value"
              :disabled="props.disabled"
              @input="updateLabelFilter(filter.id, { value: ($event.target as HTMLInputElement).value })"
            />

            <button
              type="button"
              class="flex items-center justify-center w-7 h-7 bg-transparent border-none rounded text-[var(--color-outline)] cursor-pointer transition-all duration-200 hover:enabled:bg-[var(--color-error)]/10 hover:enabled:text-[var(--color-error)]"
              :disabled="props.disabled"
              @click="removeLabelFilter(filter.id)"
            >
              <X :size="14" />
            </button>
          </div>

          <span v-if="loadingLabelValues" class="text-xs text-[var(--color-outline)]">Loading indexed values...</span>
        </div>
      </div>

      <div class="flex flex-col gap-2">
        <label class="text-sm font-medium text-[var(--color-on-surface)]">{{ lineFilterLabel }}</label>
        <div class="flex items-center gap-2">
          <select
            v-model="lineFilterOperator"
            data-testid="logql-line-filter-operator-select"
            class="w-[120px] flex-none rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm font-mono text-[var(--color-on-surface-variant)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
            :disabled="props.disabled"
          >
            <option v-for="operator in textOperators" :key="operator.value" :value="operator.value">
              {{ operator.label }}
            </option>
          </select>
          <input
            v-model="lineFilterValue"
            data-testid="logql-line-filter-value-input"
            class="flex-1 min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
            type="text"
            :placeholder="lineFilterPlaceholder"
            :disabled="props.disabled"
          />
        </div>
      </div>

      <div class="flex flex-col gap-2 mt-2 pt-4">
        <label class="text-sm font-medium text-[var(--color-on-surface)]">{{ generatedQueryLabel }}</label>
        <div class="rounded-sm bg-[var(--color-surface-container-high)] px-4 py-3 min-h-[48px]">
          <code v-if="generatedQuery" class="font-mono text-sm text-[var(--color-primary)] break-all">{{ generatedQuery }}</code>
          <span v-else class="text-[var(--color-outline)] text-sm">Add a field/value filter to generate a query</span>
        </div>
      </div>
    </div>

    <div v-else class="flex flex-col gap-4">
      <label class="text-sm font-medium text-[var(--color-on-surface)]">{{ codeEditorLabel }}</label>
      <MonacoQueryEditor
        v-model="codeQuery"
        :disabled="props.disabled"
        :height="props.editorHeight"
        :placeholder="props.placeholder"
        :language="props.queryLanguage"
        :indexed-labels="props.indexedLabels"
        @submit="emitSubmit"
      />
    </div>
  </div>
</template>
