// frontend/src/components/OnboardingBanner.tsx
import { Check, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router'

const STORAGE_KEY = 'ace-onboarding-dismissed'

const steps = [
  { label: 'Connect a data source', route: '/app/datasources/new' },
  { label: 'Create your first dashboard', route: '/app/dashboards' },
  { label: 'Set up alerts', route: '/app/alerts' },
] as const

export function OnboardingBanner() {
  const [isDismissed, setIsDismissed] = useState(() => localStorage.getItem(STORAGE_KEY) === 'true')

  if (isDismissed) return null

  function dismiss() {
    localStorage.setItem(STORAGE_KEY, 'true')
    setIsDismissed(true)
  }

  return (
    <div
      data-testid="onboarding-banner"
      className="relative rounded-xl p-5"
      style={{
        backgroundColor: 'var(--color-surface-container)',
        border: '1px solid var(--color-outline-variant)',
      }}
    >
      <button
        type="button"
        className="absolute top-3 right-3 cursor-pointer rounded-md border-none bg-transparent p-1 transition-opacity"
        style={{ color: 'var(--color-on-surface-variant)' }}
        data-testid="onboarding-dismiss"
        onClick={dismiss}
        aria-label="Dismiss onboarding"
      >
        <X size={16} aria-hidden />
      </button>

      <h2
        className="mb-4 font-display text-lg font-semibold"
        style={{ color: 'var(--color-on-surface)' }}
      >
        Get started with Ace
      </h2>

      <div className="flex flex-col gap-2">
        {steps.map((step, index) => (
          <Link
            key={step.label}
            to={step.route}
            className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm no-underline transition-colors hover:opacity-90"
            style={{
              backgroundColor: 'var(--color-surface-container-high)',
              color: 'var(--color-on-surface)',
            }}
          >
            <span
              className="flex size-5 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold"
              style={{
                backgroundColor: 'var(--color-surface-container)',
                color: 'var(--color-on-surface-variant)',
                border: '1px solid var(--color-outline-variant)',
              }}
            >
              {index + 1}
            </span>
            <span className="flex-1">{step.label}</span>
            <Check size={14} aria-hidden style={{ color: 'var(--color-outline)', opacity: 0.4 }} />
          </Link>
        ))}
      </div>
    </div>
  )
}

// frontend/src/components/OnboardingBanner.vue
<script setup lang="ts">
import { Check, X } from 'lucide-vue-next'
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const STORAGE_KEY = 'ace-onboarding-dismissed'
const router = useRouter()

const isDismissed = ref(localStorage.getItem(STORAGE_KEY) === 'true')

interface OnboardingStep {
  label: string
  route: string
  completed: boolean
}

const steps = ref<OnboardingStep[]>([
  { label: 'Connect a data source', route: '/app/datasources/new', completed: false },
  { label: 'Create your first dashboard', route: '/app/dashboards', completed: false },
  { label: 'Set up alerts', route: '/app/alerts', completed: false },
])

function dismiss() {
  isDismissed.value = true
  localStorage.setItem(STORAGE_KEY, 'true')
}

function navigateToStep(step: OnboardingStep) {
  router.push(step.route)
}
</script>

<template>
  <div
    v-if="!isDismissed"
    data-testid="onboarding-banner"
    class="rounded-xl p-5 relative"
    :style="{
      backgroundColor: 'var(--color-surface-container)',
      border: '1px solid var(--color-outline-variant)',
    }"
  >
    <!-- Dismiss button -->
    <button
      class="absolute top-3 right-3 p-1 rounded-md border-none cursor-pointer transition-opacity"
      :style="{ color: 'var(--color-on-surface-variant)', backgroundColor: 'transparent' }"
      data-testid="onboarding-dismiss"
      @click="dismiss"
    >
      <X :size="16" />
    </button>

    <h3
      class="text-sm font-semibold mb-3 mt-0"
      :style="{ color: 'var(--color-on-surface)', fontFamily: 'var(--font-display)' }"
    >
      Getting Started
    </h3>

    <div class="flex flex-col gap-2">
      <button
        v-for="(step, index) in steps"
        :key="index"
        class="flex items-center gap-3 px-3 py-2 rounded-lg text-left border-none cursor-pointer transition-colors w-full"
        :style="{
          backgroundColor: step.completed
            ? 'var(--color-surface-container-low)'
            : index === steps.findIndex(s => !s.completed)
              ? 'var(--color-surface-container-high)'
              : 'transparent',
          color: step.completed
            ? 'var(--color-on-surface-variant)'
            : 'var(--color-on-surface)',
          borderLeft: index === steps.findIndex(s => !s.completed)
            ? '3px solid var(--color-primary)'
            : step.completed
              ? '3px solid var(--color-secondary)'
              : '3px solid transparent',
        }"
        :data-testid="`onboarding-step-${index}`"
        @click="navigateToStep(step)"
      >
        <div
          v-if="step.completed"
          class="flex items-center justify-center w-5 h-5 rounded-full shrink-0"
          :style="{ backgroundColor: 'var(--color-secondary)', color: 'var(--color-on-secondary)' }"
        >
          <Check :size="12" />
        </div>
        <div
          v-else
          class="flex items-center justify-center w-5 h-5 rounded-full shrink-0 text-xs font-bold"
          :style="{
            border: '2px solid var(--color-outline-variant)',
            color: 'var(--color-on-surface-variant)',
          }"
        >
          {{ index + 1 }}
        </div>
        <span class="text-sm">{{ step.label }}</span>
      </button>
    </div>
  </div>
</template>
