// frontend/src/components/QueryBuilder.tsx
import { ChevronDown, ChevronUp, Code, Layers, Plus, Search, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { MonacoQueryEditor } from '@/components/MonacoQueryEditor'
import {
  AGGREGATION_FUNCTIONS,
  LABEL_OPERATORS,
  type LabelFilter,
  useQueryBuilder,
} from '@/hooks/useQueryBuilder'

const MAX_LABEL_VALUES = 500

type QueryBuilderProps = {
  value: string
  onChange: (value: string) => void
  disabled?: boolean
  datasourceId?: string
}

export function QueryBuilder({
  value,
  onChange,
  disabled = false,
  datasourceId = '',
}: QueryBuilderProps) {
  const {
    mode,
    setMode,
    metric,
    setMetric,
    labelFilters,
    aggregation,
    setAggregation,
    groupByLabels,
    rangeInterval,
    setRangeInterval,
    kValue,
    setKValue,
    codeQuery,
    setCodeQuery,
    generatedQuery,
    activeQuery,
    metricsCache,
    labelsCache,
    labelValuesCache,
    loadingMetrics,
    loadingLabelValues,
    setDatasourceId,
    loadMetrics,
    loadLabels,
    loadLabelValues,
    addLabelFilter,
    removeLabelFilter,
    updateLabelFilter,
    toggleGroupByLabel,
    setQuery,
  } = useQueryBuilder(value, datasourceId)

  const isEmittingRef = useRef(false)
  const [metricSearch, setMetricSearch] = useState('')
  const [showMetricDropdown, setShowMetricDropdown] = useState(false)
  const [showGroupBy, setShowGroupBy] = useState(false)

  const filteredMetrics = useMemo(() => {
    if (!metricSearch) return metricsCache.slice(0, 100)
    const search = metricSearch.toLowerCase()
    return metricsCache.filter(m => m.toLowerCase().includes(search)).slice(0, 100)
  }, [metricSearch, metricsCache])

  const availableLabelsForGroupBy = useMemo(
    () => labelsCache.filter(label => label !== '__name__'),
    [labelsCache],
  )

  const aggregationRequiresRange = useMemo(() => {
    const func = AGGREGATION_FUNCTIONS.find(f => f.value === aggregation)
    return Boolean(func && 'requiresRange' in func && func.requiresRange)
  }, [aggregation])

  const aggregationRequiresK = useMemo(() => {
    const func = AGGREGATION_FUNCTIONS.find(f => f.value === aggregation)
    return Boolean(func && 'requiresK' in func && func.requiresK)
  }, [aggregation])

  const builderAvailable = useMemo(() => {
    if (!codeQuery) return true
    if (mode === 'builder' && generatedQuery) return true
    if (codeQuery === generatedQuery) return true
    if (codeQuery && !metric) return false
    return true
  }, [codeQuery, generatedQuery, metric, mode])

  useEffect(() => {
    if (datasourceId) {
      setDatasourceId(datasourceId)
      void Promise.all([loadMetrics(), loadLabels()])
    }
  }, [datasourceId, loadLabels, loadMetrics, setDatasourceId])

  useEffect(() => {
    if (isEmittingRef.current) return
    if (value !== activeQuery) {
      setQuery(value)
    }
  }, [value, activeQuery, setQuery])

  useEffect(() => {
    isEmittingRef.current = true
    onChange(activeQuery)
    const timer = window.setTimeout(() => {
      isEmittingRef.current = false
    }, 0)
    return () => clearTimeout(timer)
  }, [activeQuery, onChange])

  function selectMetric(nextMetric: string) {
    setMetric(nextMetric)
    setMetricSearch('')
    setShowMetricDropdown(false)
  }

  function hideMetricDropdownDelayed() {
    window.setTimeout(() => setShowMetricDropdown(false), 200)
  }

  async function handleLabelChange(filter: LabelFilter, newLabel: string) {
    updateLabelFilter(filter.id, { label: newLabel, value: '' })
    if (newLabel) {
      await loadLabelValues(newLabel)
    }
  }

  function getLabelValues(labelName: string): string[] {
    const values = labelValuesCache.get(labelName) || []
    return values.slice(0, MAX_LABEL_VALUES)
  }

  return (
    <div
      className={`flex flex-col gap-4 ${disabled ? 'pointer-events-none opacity-60' : ''}`}
      data-testid="query-builder"
    >
      <div className="flex w-fit rounded-sm bg-[var(--color-surface-container-high)] p-1">
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-sm border-none bg-transparent px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:text-[var(--color-on-surface)] disabled:cursor-not-allowed disabled:opacity-40 ${mode === 'builder' ? 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm' : ''}`}
          data-testid="query-builder-mode-btn"
          onClick={() => setMode('builder')}
          disabled={disabled || !builderAvailable}
          title={!builderAvailable ? 'Query cannot be edited in builder mode' : ''}
        >
          <Layers size={14} />
          <span>Builder</span>
        </button>
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-sm border-none bg-transparent px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:text-[var(--color-on-surface)] disabled:cursor-not-allowed disabled:opacity-40 ${mode === 'code' ? 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm' : ''}`}
          data-testid="query-code-mode-btn"
          onClick={() => setMode('code')}
          disabled={disabled}
        >
          <Code size={14} />
          <span>Code</span>
        </button>
      </div>

      {mode === 'builder' ? (
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-[var(--color-on-surface)]">Metric</label>
            <div className="relative">
              <div className="relative flex items-center">
                <Search
                  size={14}
                  className="pointer-events-none absolute left-3 text-[var(--color-outline)]"
                />
                <input
                  value={metricSearch}
                  onChange={event => setMetricSearch(event.target.value)}
                  type="text"
                  data-testid="query-metric-search-input"
                  className="w-full rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 pl-9 text-sm text-[var(--color-on-surface)] transition-colors duration-200 focus:ring-2 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                  placeholder="Search metrics..."
                  disabled={disabled || loadingMetrics}
                  onFocus={() => setShowMetricDropdown(true)}
                  onBlur={hideMetricDropdownDelayed}
                />
                {metric ? (
                  <span className="absolute right-3 rounded bg-[var(--color-primary)] px-2 py-0.5 font-mono text-xs text-white">
                    {metric}
                  </span>
                ) : null}
              </div>

              {showMetricDropdown && filteredMetrics.length > 0 ? (
                <div className="absolute top-[calc(100%+4px)] right-0 left-0 z-[100] max-h-[250px] overflow-y-auto rounded-sm bg-[var(--color-surface-container-low)] shadow-lg">
                  {filteredMetrics.map(m => (
                    <div
                      key={m}
                      className={`cursor-pointer px-3 py-2 font-mono text-sm text-[var(--color-on-surface)] transition-colors duration-150 hover:bg-[var(--color-surface-container-high)] ${m === metric ? 'bg-[var(--color-primary)]/10 text-[var(--color-primary)]' : ''}`}
                      onMouseDown={event => {
                        event.preventDefault()
                        selectMetric(m)
                      }}
                    >
                      {m}
                    </div>
                  ))}
                  {loadingMetrics ? (
                    <div className="py-3 text-center text-sm text-[var(--color-outline)]">
                      Loading...
                    </div>
                  ) : null}
                </div>
              ) : null}
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-[var(--color-on-surface)]">
                Label Filters
              </label>
              <button
                type="button"
                className="flex items-center gap-1.5 rounded-sm px-3 py-1.5 text-xs font-medium text-[var(--color-on-surface-variant)] transition-all duration-200 hover:enabled:bg-[var(--color-surface-container-high)] hover:enabled:text-[var(--color-on-surface)]"
                data-testid="query-add-filter-btn"
                onClick={addLabelFilter}
                disabled={disabled}
              >
                <Plus size={14} />
                <span>Add Filter</span>
              </button>
            </div>

            {labelFilters.length === 0 ? (
              <div className="rounded-sm bg-[var(--color-surface-container-high)] p-4 text-center text-sm text-[var(--color-outline)]">
                No label filters. Click &quot;Add Filter&quot; to filter by labels.
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                {labelFilters.map(filter => (
                  <div key={filter.id} className="flex items-center gap-2">
                    <select
                      value={filter.label}
                      onChange={event => handleLabelChange(filter, event.target.value)}
                      className="min-w-0 flex-1 cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                      disabled={disabled}
                    >
                      <option value="">Select label</option>
                      {labelsCache.map(label => (
                        <option key={label} value={label}>
                          {label}
                        </option>
                      ))}
                    </select>

                    <select
                      value={filter.operator}
                      onChange={event =>
                        updateLabelFilter(filter.id, {
                          operator: event.target.value as LabelFilter['operator'],
                        })
                      }
                      className="w-[70px] flex-none cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 font-mono text-sm text-[var(--color-on-surface-variant)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                      disabled={disabled}
                    >
                      {LABEL_OPERATORS.map(op => (
                        <option key={op.value} value={op.value}>
                          {op.label}
                        </option>
                      ))}
                    </select>

                    {getLabelValues(filter.label).length > 0 ? (
                      <select
                        value={filter.value}
                        onChange={event =>
                          updateLabelFilter(filter.id, { value: event.target.value })
                        }
                        className="min-w-0 flex-[1.5] cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                        disabled={disabled || loadingLabelValues === filter.label}
                      >
                        <option value="">Select value</option>
                        {getLabelValues(filter.label).map(v => (
                          <option key={v} value={v}>
                            {v}
                          </option>
                        ))}
                      </select>
                    ) : (
                      <input
                        type="text"
                        value={filter.value}
                        onChange={event =>
                          updateLabelFilter(filter.id, { value: event.target.value })
                        }
                        className="min-w-0 flex-[1.5] rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                        placeholder="Value"
                        disabled={disabled}
                      />
                    )}

                    <button
                      type="button"
                      className="flex h-7 w-7 cursor-pointer items-center justify-center rounded border-none bg-transparent text-[var(--color-outline)] transition-all duration-200 hover:enabled:bg-[var(--color-error)]/10 hover:enabled:text-[var(--color-error)]"
                      onClick={() => removeLabelFilter(filter.id)}
                      disabled={disabled}
                    >
                      <X size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-[var(--color-on-surface)]">
              Aggregation
            </label>
            <div className="flex items-center gap-4">
              <select
                value={aggregation}
                onChange={event => setAggregation(event.target.value as typeof aggregation)}
                data-testid="query-aggregation-select"
                className="max-w-[200px] flex-1 cursor-pointer rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                disabled={disabled}
              >
                {AGGREGATION_FUNCTIONS.map(agg => (
                  <option key={agg.value} value={agg.value}>
                    {agg.label}
                  </option>
                ))}
              </select>

              {aggregationRequiresRange ? (
                <div className="flex items-center gap-2">
                  <label className="text-sm text-[var(--color-outline)]">Range:</label>
                  <input
                    value={rangeInterval}
                    onChange={event => setRangeInterval(event.target.value)}
                    type="text"
                    data-testid="query-range-input"
                    className="w-20 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 font-mono text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                    placeholder="5m"
                    disabled={disabled}
                  />
                </div>
              ) : null}

              {aggregationRequiresK ? (
                <div className="flex items-center gap-2">
                  <label className="text-sm text-[var(--color-outline)]">K:</label>
                  <input
                    value={kValue}
                    onChange={event => setKValue(Number(event.target.value))}
                    type="number"
                    min={1}
                    data-testid="query-k-input"
                    className="w-[60px] rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)]/20 focus:outline-none"
                    disabled={disabled}
                  />
                </div>
              ) : null}
            </div>
          </div>

          {aggregation ? (
            <div className="flex flex-col gap-2">
              <button
                type="button"
                className="flex w-full cursor-pointer items-center gap-2 border-none bg-transparent py-2 text-[var(--color-on-surface)] hover:text-[var(--color-primary)]"
                onClick={() => setShowGroupBy(prev => !prev)}
                disabled={disabled}
              >
                <span className="text-sm font-medium">Group By</span>
                {groupByLabels.length > 0 ? (
                  <span className="inline-flex h-5 min-w-[20px] items-center justify-center rounded-sm bg-[var(--color-primary)] px-1.5 text-xs font-medium text-white">
                    {groupByLabels.length}
                  </span>
                ) : null}
                {showGroupBy ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>

              {showGroupBy ? (
                <div className="rounded-sm bg-[var(--color-surface-container-high)] p-3">
                  <div className="flex flex-wrap gap-2">
                    {availableLabelsForGroupBy.map(label => (
                      <label
                        key={label}
                        className="flex cursor-pointer items-center gap-1.5 rounded bg-[var(--color-surface-container-low)] px-2.5 py-1.5 text-xs text-[var(--color-on-surface)] transition-all duration-200 hover:border-[var(--color-primary)]/20"
                      >
                        <input
                          type="checkbox"
                          checked={groupByLabels.includes(label)}
                          onChange={() => toggleGroupByLabel(label)}
                          disabled={disabled}
                        />
                        <span>{label}</span>
                      </label>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}

          <div className="mt-2 flex flex-col gap-2 pt-4">
            <label className="text-sm font-medium text-[var(--color-on-surface)]">
              Generated Query
            </label>
            <div className="min-h-[48px] rounded-sm bg-[var(--color-surface-container-high)] px-4 py-3">
              {generatedQuery ? (
                <code className="font-mono text-sm break-all text-[var(--color-primary)]">
                  {generatedQuery}
                </code>
              ) : (
                <span className="text-sm text-[var(--color-outline)]">
                  Select a metric to generate query
                </span>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <label className="text-sm font-medium text-[var(--color-on-surface)]">Query</label>
          <MonacoQueryEditor
            value={codeQuery}
            onChange={setCodeQuery}
            disabled={disabled}
            height={120}
            placeholder="Enter query (PromQL / MetricsQL)..."
          />
        </div>
      )}
    </div>
  )
}

// frontend/src/components/QueryBuilder.vue
<script setup lang="ts">
import { ChevronDown, ChevronUp, Code, Layers, Plus, Search, X } from 'lucide-vue-next'
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import {
  AGGREGATION_FUNCTIONS,
  LABEL_OPERATORS,
  type LabelFilter,
  useQueryBuilder,
} from '../composables/useQueryBuilder'
import MonacoQueryEditor from './MonacoQueryEditor.vue'

const props = defineProps<{
  modelValue: string
  disabled?: boolean
  datasourceId?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const {
  mode,
  metric,
  labelFilters,
  aggregation,
  groupByLabels,
  rangeInterval,
  kValue,
  codeQuery,
  generatedQuery,
  activeQuery,
  metricsCache,
  labelsCache,
  labelValuesCache,
  loadingMetrics,
  loadingLabelValues,
  setDatasourceId,
  loadMetrics,
  loadLabels,
  loadLabelValues,
  addLabelFilter,
  removeLabelFilter,
  updateLabelFilter,
  toggleGroupByLabel,
  setQuery,
} = useQueryBuilder(props.modelValue, props.datasourceId)

// Track when we're emitting to avoid reacting to our own changes
const isEmitting = ref(false)

// Metric search
const metricSearch = ref('')
const showMetricDropdown = ref(false)

const filteredMetrics = computed(() => {
  if (!metricSearch.value) return metricsCache.value.slice(0, 100)
  const search = metricSearch.value.toLowerCase()
  return metricsCache.value.filter((m) => m.toLowerCase().includes(search)).slice(0, 100)
})

// Group by expanded state
const showGroupBy = ref(false)

// Available labels for group by (exclude __name__)
const availableLabelsForGroupBy = computed(() => {
  return labelsCache.value.filter((l) => l !== '__name__')
})

// Check if aggregation requires range
const aggregationRequiresRange = computed(() => {
  const func = AGGREGATION_FUNCTIONS.find((f) => f.value === aggregation.value)
  return func && 'requiresRange' in func && func.requiresRange
})

// Check if aggregation requires K value
const aggregationRequiresK = computed(() => {
  const func = AGGREGATION_FUNCTIONS.find((f) => f.value === aggregation.value)
  return func && 'requiresK' in func && func.requiresK
})

// Check if builder mode is available
// Builder is unavailable if there's a code query that can't be represented in builder
const builderAvailable = computed(() => {
  // If there's no query, builder is available
  if (!codeQuery.value) return true
  // If we're in builder mode with a generated query, builder is available
  if (mode.value === 'builder' && generatedQuery.value) return true
  // If the code query matches the generated query, builder is available
  if (codeQuery.value === generatedQuery.value) return true
  // If there's a code query but no metric selected (can't parse), builder is unavailable
  if (codeQuery.value && !metric.value) return false
  return true
})

// Load metadata on mount
onMounted(async () => {
  if (props.datasourceId) {
    await Promise.all([loadMetrics(), loadLabels()])
  }
})

// Reload metadata when datasource changes
watch(
  () => props.datasourceId,
  async (newId) => {
    if (newId) {
      setDatasourceId(newId)
      await Promise.all([loadMetrics(), loadLabels()])
    }
  },
)

// Sync with v-model
watch(
  () => props.modelValue,
  (newValue) => {
    // Ignore changes triggered by our own emit
    if (isEmitting.value) return
    if (newValue !== activeQuery.value) {
      setQuery(newValue)
    }
  },
)

watch(activeQuery, (newValue) => {
  isEmitting.value = true
  emit('update:modelValue', newValue)
  nextTick(() => {
    isEmitting.value = false
  })
})

// Select metric
function selectMetric(m: string) {
  metric.value = m
  metricSearch.value = ''
  showMetricDropdown.value = false
}

// Delay hiding metric dropdown (to allow click events to fire)
function hideMetricDropdownDelayed() {
  setTimeout(() => {
    showMetricDropdown.value = false
  }, 200)
}

// Handle label filter label change - preload values
async function handleLabelChange(filter: LabelFilter, newLabel: string) {
  updateLabelFilter(filter.id, { label: newLabel, value: '' })
  if (newLabel) {
    await loadLabelValues(newLabel)
  }
}

// Get cached label values (capped for performance)
const MAX_LABEL_VALUES = 500

function getLabelValues(labelName: string): string[] {
  const values = labelValuesCache.value.get(labelName) || []
  return values.slice(0, MAX_LABEL_VALUES)
}
</script>

<template>
  <div class="flex flex-col gap-4" :class="{ 'opacity-60 pointer-events-none': disabled }">
    <!-- Mode Toggle -->
    <div class="flex rounded-sm bg-[var(--color-surface-container-high)] p-1 w-fit">
      <button
        type="button"
        class="flex items-center gap-1.5 px-3 py-1.5 bg-transparent border-none rounded-sm text-xs font-medium text-[var(--color-on-surface-variant)] cursor-pointer transition-all duration-200 disabled:opacity-40 disabled:cursor-not-allowed hover:enabled:text-[var(--color-on-surface)]"
        :class="{ 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm': mode === 'builder' }"
        data-testid="query-builder-mode-btn"
        @click="mode = 'builder'"
        :disabled="disabled || !builderAvailable"
        :title="!builderAvailable ? 'Query cannot be edited in builder mode' : ''"
      >
        <Layers :size="14" />
        <span>Builder</span>
      </button>
      <button
        type="button"
        class="flex items-center gap-1.5 px-3 py-1.5 bg-transparent border-none rounded-sm text-xs font-medium text-[var(--color-on-surface-variant)] cursor-pointer transition-all duration-200 disabled:opacity-40 disabled:cursor-not-allowed hover:enabled:text-[var(--color-on-surface)]"
        :class="{ 'bg-[var(--color-surface-container-low)] text-[var(--color-on-surface)] shadow-sm': mode === 'code' }"
        data-testid="query-code-mode-btn"
        @click="mode = 'code'"
        :disabled="disabled"
      >
        <Code :size="14" />
        <span>Code</span>
      </button>
    </div>

    <!-- Builder Mode -->
    <div v-if="mode === 'builder'" class="flex flex-col gap-4">
      <!-- Metric Selector -->
      <div class="flex flex-col gap-2">
        <label class="text-sm font-medium text-[var(--color-on-surface)]">Metric</label>
        <div class="relative">
          <div class="relative flex items-center">
            <Search :size="14" class="absolute left-3 text-[var(--color-outline)] pointer-events-none" />
            <input
              v-model="metricSearch"
              type="text"
              data-testid="query-metric-search-input"
              class="w-full rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 pl-9 text-sm text-[var(--color-on-surface)] transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary)]/20"
              placeholder="Search metrics..."
              :disabled="disabled || loadingMetrics"
              @focus="showMetricDropdown = true"
              @blur="hideMetricDropdownDelayed"
            />
            <span v-if="metric" class="absolute right-3 rounded bg-[var(--color-primary)] px-2 py-0.5 text-xs font-mono text-white">{{ metric }}</span>
          </div>

          <div v-if="showMetricDropdown && filteredMetrics.length > 0" class="absolute top-[calc(100%+4px)] left-0 right-0 max-h-[250px] overflow-y-auto bg-[var(--color-surface-container-low)] rounded-sm shadow-lg z-[100]">
            <div
              v-for="m in filteredMetrics"
              :key="m"
              class="px-3 py-2 text-sm font-mono text-[var(--color-on-surface)] cursor-pointer transition-colors duration-150 hover:bg-[var(--color-surface-container-high)]"
              :class="{ 'bg-[var(--color-primary)]/10 text-[var(--color-primary)]': m === metric }"
              @mousedown.prevent="selectMetric(m)"
            >
              {{ m }}
            </div>
            <div v-if="loadingMetrics" class="py-3 text-center text-[var(--color-outline)] text-sm">Loading...</div>
          </div>
        </div>
      </div>

      <!-- Label Filters -->
      <div class="flex flex-col gap-2">
        <div class="flex justify-between items-center">
          <label class="text-sm font-medium text-[var(--color-on-surface)]">Label Filters</label>
          <button
            type="button"
            class="flex items-center gap-1.5 px-3 py-1.5 rounded-sm text-xs font-medium text-[var(--color-on-surface-variant)] cursor-pointer transition-all duration-200 hover:enabled:bg-[var(--color-surface-container-high)] hover:enabled:text-[var(--color-on-surface)]"
            data-testid="query-add-filter-btn"
            @click="addLabelFilter"
            :disabled="disabled"
          >
            <Plus :size="14" />
            <span>Add Filter</span>
          </button>
        </div>

        <div v-if="labelFilters.length === 0" class="p-4 text-center text-[var(--color-outline)] text-sm bg-[var(--color-surface-container-high)] rounded-sm">
          No label filters. Click "Add Filter" to filter by labels.
        </div>

        <div v-else class="flex flex-col gap-2">
          <div
            v-for="filter in labelFilters"
            :key="filter.id"
            class="flex gap-2 items-center"
          >
            <!-- Label select -->
            <select
              :value="filter.label"
              @change="handleLabelChange(filter, ($event.target as HTMLSelectElement).value)"
              class="flex-1 min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :disabled="disabled"
            >
              <option value="">Select label</option>
              <option v-for="label in labelsCache" :key="label" :value="label">
                {{ label }}
              </option>
            </select>

            <!-- Operator select -->
            <select
              :value="filter.operator"
              @change="updateLabelFilter(filter.id, { operator: ($event.target as HTMLSelectElement).value as any })"
              class="w-[70px] flex-none rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm font-mono text-[var(--color-on-surface-variant)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :disabled="disabled"
            >
              <option v-for="op in LABEL_OPERATORS" :key="op.value" :value="op.value">
                {{ op.label }}
              </option>
            </select>

            <!-- Value select/input -->
            <select
              v-if="getLabelValues(filter.label).length > 0"
              :value="filter.value"
              @change="updateLabelFilter(filter.id, { value: ($event.target as HTMLSelectElement).value })"
              class="flex-[1.5] min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :disabled="disabled || loadingLabelValues === filter.label"
            >
              <option value="">Select value</option>
              <option v-for="v in getLabelValues(filter.label)" :key="v" :value="v">
                {{ v }}
              </option>
            </select>
            <input
              v-else
              type="text"
              :value="filter.value"
              @input="updateLabelFilter(filter.id, { value: ($event.target as HTMLInputElement).value })"
              class="flex-[1.5] min-w-0 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              placeholder="Value"
              :disabled="disabled"
            />

            <!-- Remove button -->
            <button
              type="button"
              class="flex items-center justify-center w-7 h-7 bg-transparent border-none rounded text-[var(--color-outline)] cursor-pointer transition-all duration-200 hover:enabled:bg-[var(--color-error)]/10 hover:enabled:text-[var(--color-error)]"
              @click="removeLabelFilter(filter.id)"
              :disabled="disabled"
            >
              <X :size="14" />
            </button>
          </div>
        </div>
      </div>

      <!-- Aggregation -->
      <div class="flex flex-col gap-2">
        <label class="text-sm font-medium text-[var(--color-on-surface)]">Aggregation</label>
        <div class="flex gap-4 items-center">
          <select
            v-model="aggregation"
            data-testid="query-aggregation-select"
            class="flex-1 max-w-[200px] rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] cursor-pointer focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
            :disabled="disabled"
          >
            <option v-for="agg in AGGREGATION_FUNCTIONS" :key="agg.value" :value="agg.value">
              {{ agg.label }}
            </option>
          </select>

          <!-- Range input for rate/increase functions -->
          <div v-if="aggregationRequiresRange" class="flex items-center gap-2">
            <label class="text-sm text-[var(--color-outline)]">Range:</label>
            <input
              v-model="rangeInterval"
              type="text"
              data-testid="query-range-input"
              class="w-20 rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm font-mono text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              placeholder="5m"
              :disabled="disabled"
            />
          </div>

          <!-- K value for topk/bottomk -->
          <div v-if="aggregationRequiresK" class="flex items-center gap-2">
            <label class="text-sm text-[var(--color-outline)]">K:</label>
            <input
              v-model.number="kValue"
              type="number"
              min="1"
              data-testid="query-k-input"
              class="w-[60px] rounded-sm bg-[var(--color-surface-container-high)] px-3 py-2 text-sm text-[var(--color-on-surface)] focus:outline-none focus:ring-1 focus:ring-[var(--color-primary)]/20"
              :disabled="disabled"
            />
          </div>
        </div>
      </div>

      <!-- Group By -->
      <div v-if="aggregation" class="flex flex-col gap-2">
        <button
          type="button"
          class="flex items-center gap-2 py-2 bg-transparent border-none cursor-pointer text-[var(--color-on-surface)] w-full hover:text-[var(--color-primary)]"
          @click="showGroupBy = !showGroupBy"
          :disabled="disabled"
        >
          <span class="text-sm font-medium">Group By</span>
          <span v-if="groupByLabels.length > 0" class="inline-flex items-center justify-center min-w-[20px] h-5 px-1.5 bg-[var(--color-primary)] rounded-sm text-xs font-medium text-white">{{ groupByLabels.length }}</span>
          <component :is="showGroupBy ? ChevronUp : ChevronDown" :size="14" />
        </button>

        <div v-if="showGroupBy" class="p-3 bg-[var(--color-surface-container-high)] rounded-sm">
          <div class="flex flex-wrap gap-2">
            <label
              v-for="label in availableLabelsForGroupBy"
              :key="label"
              class="flex items-center gap-1.5 px-2.5 py-1.5 bg-[var(--color-surface-container-low)] rounded text-xs text-[var(--color-on-surface)] cursor-pointer transition-all duration-200 hover:border-[var(--color-primary)]/20"
            >
              <input
                type="checkbox"
                :checked="groupByLabels.includes(label)"
                @change="toggleGroupByLabel(label)"
                :disabled="disabled"
                class="[var(--color-primary)]"
              />
              <span>{{ label }}</span>
            </label>
          </div>
        </div>
      </div>

      <!-- Preview -->
      <div class="flex flex-col gap-2 mt-2 pt-4">
        <label class="text-sm font-medium text-[var(--color-on-surface)]">Generated Query</label>
        <div class="rounded-sm bg-[var(--color-surface-container-high)] px-4 py-3 min-h-[48px]">
          <code v-if="generatedQuery" class="font-mono text-sm text-[var(--color-primary)] break-all">{{ generatedQuery }}</code>
          <span v-else class="text-[var(--color-outline)] text-sm">Select a metric to generate query</span>
        </div>
      </div>
    </div>

    <!-- Code Mode -->
    <div v-else class="flex flex-col gap-4">
      <label class="text-sm font-medium text-[var(--color-on-surface)]">Query</label>
      <MonacoQueryEditor
        v-model="codeQuery"
        :disabled="disabled"
        :height="120"
        placeholder="Enter query (PromQL / MetricsQL)..."
      />
    </div>
  </div>
</template>
