// frontend/src/components/ShortcutsOverlay.tsx
import { useMemo } from 'react'
import { useKeyboardShortcutsStore } from '@/lib/keyboardShortcuts'

export function ShortcutsOverlay() {
  const showHelp = useKeyboardShortcutsStore(state => state.showHelp)
  const shortcuts = useKeyboardShortcutsStore(state => state.shortcuts)
  const setShowHelp = useKeyboardShortcutsStore(state => state.setShowHelp)

  const groupedShortcuts = useMemo(() => {
    const groups: Record<string, typeof shortcuts> = {}
    for (const shortcut of shortcuts) {
      groups[shortcut.category] ??= []
      groups[shortcut.category].push(shortcut)
    }
    return groups
  }, [shortcuts])

  if (!showHelp) return null

  function close() {
    setShowHelp(false)
  }

  function handleKeydown(e: React.KeyboardEvent) {
    if (e.key === 'Escape') close()
  }

  return (
    <div onKeyDown={handleKeydown}>
      <div
        className="fixed inset-0 z-50"
        style={{
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
          backdropFilter: 'blur(4px)',
        }}
        onClick={close}
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Keyboard shortcuts"
        className="fixed top-1/2 left-1/2 z-50 w-full -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-xl p-6 shadow-2xl"
        style={{
          maxWidth: '480px',
          backgroundColor: 'color-mix(in srgb, var(--color-surface-container-highest) 85%, transparent)',
          backdropFilter: 'blur(20px)',
          border: '1px solid var(--color-outline-variant)',
        }}
      >
        <div className="mb-4 flex items-center justify-between">
          <h2
            className="m-0 text-lg font-semibold"
            style={{ color: 'var(--color-on-surface)', fontFamily: 'var(--font-display)' }}
          >
            Keyboard Shortcuts
          </h2>
          <button
            type="button"
            className="cursor-pointer rounded-md border-none p-1 text-sm"
            style={{ color: 'var(--color-on-surface-variant)', backgroundColor: 'transparent' }}
            onClick={close}
          >
            &times;
          </button>
        </div>

        <div className="flex flex-col gap-4">
          {Object.entries(groupedShortcuts).map(([category, items]) => (
            <div key={category}>
              <h3
                className="mt-0 mb-2 text-xs font-semibold tracking-wider uppercase"
                style={{ color: 'var(--color-on-surface-variant)' }}
              >
                {category}
              </h3>
              <div className="flex flex-col gap-1">
                {items.map(shortcut => (
                  <div
                    key={shortcut.keys}
                    className="flex items-center justify-between rounded-md px-2 py-1.5"
                  >
                    <span className="text-sm" style={{ color: 'var(--color-on-surface)' }}>
                      {shortcut.label}
                    </span>
                    <kbd
                      className="inline-flex items-center gap-1 rounded px-2 py-0.5 font-mono text-xs"
                      style={{
                        backgroundColor: 'var(--color-surface-container)',
                        color: 'var(--color-on-surface-variant)',
                        border: '1px solid var(--color-outline-variant)',
                      }}
                    >
                      {shortcut.keys}
                    </kbd>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/ShortcutsOverlay.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useKeyboardShortcuts, type ShortcutEntry } from '../composables/useKeyboardShortcuts'

const { shortcuts, showHelp } = useKeyboardShortcuts()

const groupedShortcuts = computed(() => {
  const groups: Record<string, ShortcutEntry[]> = {}
  for (const s of shortcuts.value) {
    if (!groups[s.category]) {
      groups[s.category] = []
    }
    groups[s.category].push(s)
  }
  return groups
})

function close() {
  showHelp.value = false
}

function handleScrimClick() {
  close()
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    close()
  }
}
</script>

<template>
  <div v-if="showHelp" @keydown="handleKeydown">
    <!-- Scrim -->
    <div
      class="fixed inset-0 z-50"
      :style="{
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(4px)',
      }"
      @click="handleScrimClick"
    />

    <!-- Panel -->
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Keyboard shortcuts"
      class="fixed left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2 w-full rounded-xl overflow-hidden shadow-2xl p-6"
      :style="{
        maxWidth: '480px',
        backgroundColor: 'color-mix(in srgb, var(--color-surface-container-highest) 85%, transparent)',
        backdropFilter: 'blur(20px)',
        border: '1px solid var(--color-outline-variant)',
      }"
    >
      <div class="flex items-center justify-between mb-4">
        <h2
          class="text-lg font-semibold m-0"
          :style="{ color: 'var(--color-on-surface)', fontFamily: 'var(--font-display)' }"
        >
          Keyboard Shortcuts
        </h2>
        <button
          class="p-1 rounded-md border-none cursor-pointer text-sm"
          :style="{ color: 'var(--color-on-surface-variant)', backgroundColor: 'transparent' }"
          @click="close"
        >
          &times;
        </button>
      </div>

      <div class="flex flex-col gap-4">
        <div v-for="(items, category) in groupedShortcuts" :key="category">
          <h3
            class="text-xs font-semibold uppercase tracking-wider mb-2 mt-0"
            :style="{ color: 'var(--color-on-surface-variant)' }"
          >
            {{ category }}
          </h3>
          <div class="flex flex-col gap-1">
            <div
              v-for="shortcut in items"
              :key="shortcut.keys"
              class="flex items-center justify-between py-1.5 px-2 rounded-md"
            >
              <span
                class="text-sm"
                :style="{ color: 'var(--color-on-surface)' }"
              >{{ shortcut.label }}</span>
              <kbd
                class="inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-mono"
                :style="{
                  backgroundColor: 'var(--color-surface-container)',
                  color: 'var(--color-on-surface-variant)',
                  border: '1px solid var(--color-outline-variant)',
                }"
              >{{ shortcut.keys }}</kbd>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
