// frontend/src/components/panels/AlertListPanel.vue
<script setup lang="ts">
import { computed } from 'vue'
import { chartPalette, thresholdColors } from '../../utils/chartTheme'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AlertItem {
  id: string
  name: string
  severity: 'critical' | 'warning' | 'info'
  state: 'firing' | 'resolved' | 'pending'
  timestamp: string // ISO timestamp
  message?: string
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  alerts: AlertItem[]
  emptyTitle?: string
  emptyDescription?: string
  emptyActionLabel?: string
}>()

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function severityColor(severity: AlertItem['severity']): string {
  if (severity === 'critical') return thresholdColors.critical
  if (severity === 'warning') return thresholdColors.warning
  return chartPalette[0] // info → Steel Blue
}

function stateBadgeStyle(state: AlertItem['state']): Record<string, string> {
  if (state === 'firing') {
    return {
      backgroundColor: `${thresholdColors.critical}22`,
      color: thresholdColors.critical,
      border: `1px solid ${thresholdColors.critical}55`,
    }
  }
  if (state === 'resolved') {
    return {
      backgroundColor: `${thresholdColors.good}22`,
      color: thresholdColors.good,
      border: `1px solid ${thresholdColors.good}55`,
    }
  }
  // pending
  return {
    backgroundColor: `${thresholdColors.warning}22`,
    color: thresholdColors.warning,
    border: `1px solid ${thresholdColors.warning}55`,
  }
}

function formatTimestamp(iso: string): string {
  const now = Date.now()
  const ts = new Date(iso).getTime()
  const diffMs = now - ts
  const diffSec = Math.floor(diffMs / 1000)

  if (diffSec < 60) return `${diffSec}s ago`
  const diffMin = Math.floor(diffSec / 60)
  if (diffMin < 60) return `${diffMin}m ago`
  const diffHr = Math.floor(diffMin / 60)
  if (diffHr < 24) return `${diffHr}h ago`
  const diffDay = Math.floor(diffHr / 24)
  return `${diffDay}d ago`
}

// ---------------------------------------------------------------------------
// Computed styles
// ---------------------------------------------------------------------------

const containerStyle = computed(() => ({
  overflowY: 'auto' as const,
  height: '100%',
  width: '100%',
  fontFamily: "'DM Sans', sans-serif",
  backgroundColor: 'transparent',
}))

const emptyStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  alignItems: 'center',
  justifyContent: 'center',
  gap: '0.35rem',
  height: '100%',
  color: 'var(--color-on-surface-variant)',
  fontSize: '0.875rem',
  textAlign: 'center' as const,
  padding: '1rem',
}

const emptyTitleStyle = {
  color: 'var(--color-on-surface)',
  fontWeight: '600',
}

const emptyDescriptionStyle = {
  maxWidth: '22rem',
  fontSize: '0.75rem',
  lineHeight: '1.35',
}

const emptyActionStyle = {
  marginTop: '0.25rem',
  fontSize: '0.6875rem',
  fontWeight: '600',
  color: 'var(--color-primary)',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.04em',
}

const rowStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '0.25rem',
  padding: '0.625rem 0.75rem',
  borderBottom: '1px solid var(--color-surface-container-high)',
}

const rowTopStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
}

const nameStyle = {
  flex: '1',
  fontSize: '0.875rem',
  fontWeight: '500',
  color: 'var(--color-on-surface)',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap' as const,
}

const timestampStyle = {
  fontSize: '0.75rem',
  color: 'var(--color-on-surface-variant)',
  flexShrink: '0',
}

const badgeBaseStyle = {
  fontSize: '0.6875rem',
  fontWeight: '600',
  padding: '0.125rem 0.4rem',
  borderRadius: '9999px',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.04em',
  flexShrink: '0',
}

const messageStyle = {
  fontSize: '0.75rem',
  color: 'var(--color-on-surface-variant)',
  paddingLeft: '1.25rem', // align under name (past the dot)
}
</script>

<template>
  <div
    data-testid="alert-list-container"
    :style="containerStyle"
  >
    <!-- Empty state -->
    <div
      v-if="props.alerts.length === 0"
      data-testid="alert-list-empty"
      :style="emptyStyle"
    >
      <div :style="emptyTitleStyle">{{ props.emptyTitle || 'No alerts' }}</div>
      <div v-if="props.emptyDescription" :style="emptyDescriptionStyle">
        {{ props.emptyDescription }}
      </div>
      <div v-if="props.emptyActionLabel" :style="emptyActionStyle">
        {{ props.emptyActionLabel }}
      </div>
    </div>

    <!-- Alert rows -->
    <div
      v-for="alert in props.alerts"
      v-else
      :key="alert.id"
      data-testid="alert-item"
      :style="rowStyle"
    >
      <!-- Top row: dot + name + badge + timestamp -->
      <div :style="rowTopStyle">
        <!-- Severity dot -->
        <span
          data-testid="severity-dot"
          :style="{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            flexShrink: '0',
            backgroundColor: severityColor(alert.severity),
          }"
        />

        <!-- Alert name -->
        <span
          data-testid="alert-name"
          :style="nameStyle"
        >
          {{ alert.name }}
        </span>

        <!-- State badge -->
        <span
          data-testid="state-badge"
          :style="{ ...badgeBaseStyle, ...stateBadgeStyle(alert.state) }"
        >
          {{ alert.state }}
        </span>

        <!-- Timestamp -->
        <span
          data-testid="alert-timestamp"
          :style="timestampStyle"
        >
          {{ formatTimestamp(alert.timestamp) }}
        </span>
      </div>

      <!-- Optional message -->
      <div
        v-if="alert.message"
        data-testid="alert-message"
        :style="messageStyle"
      >
        {{ alert.message }}
      </div>
    </div>
  </div>
</template>

// frontend/src/components/panels/react/AlertListPanel.tsx
import type { CSSProperties } from 'react'
import { chartPalette, thresholdColors } from '@/utils/chartTheme'

export type AlertItem = {
  id: string
  name: string
  severity: 'critical' | 'warning' | 'info'
  state: 'firing' | 'resolved' | 'pending'
  timestamp: string
  message?: string
}

type AlertListPanelProps = {
  alerts?: AlertItem[]
  emptyTitle?: string
  emptyDescription?: string
  emptyActionLabel?: string
}

function severityColor(severity: AlertItem['severity']): string {
  if (severity === 'critical') return thresholdColors.critical
  if (severity === 'warning') return thresholdColors.warning
  return chartPalette[0]
}

function stateBadgeStyle(state: AlertItem['state']): CSSProperties {
  if (state === 'firing') {
    return {
      backgroundColor: `${thresholdColors.critical}22`,
      color: thresholdColors.critical,
      border: `1px solid ${thresholdColors.critical}55`,
    }
  }
  if (state === 'resolved') {
    return {
      backgroundColor: `${thresholdColors.good}22`,
      color: thresholdColors.good,
      border: `1px solid ${thresholdColors.good}55`,
    }
  }
  return {
    backgroundColor: `${thresholdColors.warning}22`,
    color: thresholdColors.warning,
    border: `1px solid ${thresholdColors.warning}55`,
  }
}

function formatTimestamp(iso: string): string {
  const diffSec = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (diffSec < 60) return `${diffSec}s ago`
  const diffMin = Math.floor(diffSec / 60)
  if (diffMin < 60) return `${diffMin}m ago`
  const diffHr = Math.floor(diffMin / 60)
  if (diffHr < 24) return `${diffHr}h ago`
  return `${Math.floor(diffHr / 24)}d ago`
}

export function AlertListPanel({
  alerts = [],
  emptyTitle = 'No alerts',
  emptyDescription,
  emptyActionLabel,
}: AlertListPanelProps) {
  if (alerts.length === 0) {
    return (
      <div
        className="flex h-full w-full flex-col items-center justify-center gap-1 p-4 text-center text-sm"
        data-testid="alert-list-empty"
        style={{ color: 'var(--color-on-surface-variant)', fontFamily: "'DM Sans', sans-serif" }}
      >
        <div className="font-semibold" style={{ color: 'var(--color-on-surface)' }}>
          {emptyTitle}
        </div>
        {emptyDescription ? <div className="max-w-sm text-xs leading-5">{emptyDescription}</div> : null}
        {emptyActionLabel ? (
          <div
            className="mt-1 text-[11px] font-semibold uppercase tracking-wide"
            style={{ color: 'var(--color-primary)' }}
          >
            {emptyActionLabel}
          </div>
        ) : null}
      </div>
    )
  }

  return (
    <div
      className="h-full w-full overflow-y-auto"
      data-testid="alert-list-container"
      style={{ fontFamily: "'DM Sans', sans-serif" }}
    >
      {alerts.map(alert => (
        <div
          key={alert.id}
          data-testid="alert-item"
          className="flex flex-col gap-1 px-3 py-2.5"
          style={{ borderBottom: '1px solid var(--color-surface-container-high)' }}
        >
          <div className="flex items-center gap-2">
            <span
              data-testid="severity-dot"
              className="h-2 w-2 shrink-0 rounded-full"
              style={{ backgroundColor: severityColor(alert.severity) }}
            />
            <span
              data-testid="alert-name"
              className="min-w-0 flex-1 truncate text-sm font-medium"
              style={{ color: 'var(--color-on-surface)' }}
            >
              {alert.name}
            </span>
            <span
              data-testid="state-badge"
              className="shrink-0 rounded-full px-1.5 py-0.5 text-[11px] font-semibold uppercase tracking-wide"
              style={stateBadgeStyle(alert.state)}
            >
              {alert.state}
            </span>
            <span
              data-testid="alert-timestamp"
              className="shrink-0 text-xs"
              style={{ color: 'var(--color-on-surface-variant)' }}
            >
              {formatTimestamp(alert.timestamp)}
            </span>
          </div>
          {alert.message ? (
            <div
              data-testid="alert-message"
              className="pl-5 text-xs"
              style={{ color: 'var(--color-on-surface-variant)' }}
            >
              {alert.message}
            </div>
          ) : null}
        </div>
      ))}
    </div>
  )
}
