// frontend/src/components/panels/AnnotationListPanel.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { chartPalette, thresholdColors } from '../../utils/chartTheme'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AnnotationItem {
  id: string
  title: string
  description?: string
  timestamp: string // ISO timestamp
  type: 'deploy' | 'incident' | 'config_change' | 'other'
  tags?: string[]
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  annotations: AnnotationItem[]
  emptyTitle?: string
  emptyDescription?: string
  emptyActionLabel?: string
}>()

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function typeColor(type: AnnotationItem['type']): string {
  if (type === 'deploy') return chartPalette[0]       // Steel Blue
  if (type === 'incident') return thresholdColors.critical
  if (type === 'config_change') return thresholdColors.warning
  return chartPalette[7]                               // Alloy Silver — other
}

// Reactive clock for relative timestamps — refreshes every 60s
const now = ref(Date.now())
let ticker: ReturnType<typeof setInterval> | null = null
onMounted(() => {
  ticker = setInterval(() => {
    now.value = Date.now()
  }, 60_000)
})
onUnmounted(() => {
  if (ticker) clearInterval(ticker)
})

function formatTimestamp(iso: string): string {
  const ts = new Date(iso).getTime()
  const diffMs = now.value - ts
  const diffSec = Math.floor(diffMs / 1000)

  if (diffSec < 60) return `${diffSec}s ago`
  const diffMin = Math.floor(diffSec / 60)
  if (diffMin < 60) return `${diffMin}m ago`
  const diffHr = Math.floor(diffMin / 60)
  if (diffHr < 24) return `${diffHr}h ago`
  const diffDay = Math.floor(diffHr / 24)
  return `${diffDay}d ago`
}

// ---------------------------------------------------------------------------
// Computed styles
// ---------------------------------------------------------------------------

const containerStyle = computed(() => ({
  overflowY: 'auto' as const,
  height: '100%',
  width: '100%',
  fontFamily: "'DM Sans', sans-serif",
  backgroundColor: 'transparent',
}))

const emptyStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  alignItems: 'center',
  justifyContent: 'center',
  gap: '0.35rem',
  height: '100%',
  color: 'var(--color-on-surface-variant)',
  fontSize: '0.875rem',
  textAlign: 'center' as const,
  padding: '1rem',
}

const emptyTitleStyle = {
  color: 'var(--color-on-surface)',
  fontWeight: '600',
}

const emptyDescriptionStyle = {
  maxWidth: '22rem',
  fontSize: '0.75rem',
  lineHeight: '1.35',
}

const emptyActionStyle = {
  marginTop: '0.25rem',
  fontSize: '0.6875rem',
  fontWeight: '600',
  color: 'var(--color-primary)',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.04em',
}

const rowStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '0.25rem',
  padding: '0.625rem 0.75rem',
  borderBottom: '1px solid var(--color-surface-container-high)',
}

const rowTopStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
}

const titleStyle = {
  flex: '1',
  fontSize: '0.875rem',
  fontWeight: '500',
  color: 'var(--color-on-surface)',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap' as const,
}

const timestampStyle = {
  fontSize: '0.75rem',
  color: 'var(--color-on-surface-variant)',
  flexShrink: '0',
}

const descriptionStyle = {
  fontSize: '0.75rem',
  color: 'var(--color-on-surface-variant)',
  paddingLeft: '1.25rem', // align under title (past the dot)
}

const tagsRowStyle = {
  display: 'flex',
  flexWrap: 'wrap' as const,
  gap: '0.25rem',
  paddingLeft: '1.25rem',
}

const tagStyle = {
  fontSize: '0.6875rem',
  fontWeight: '500',
  padding: '0.125rem 0.375rem',
  borderRadius: '9999px',
  backgroundColor: 'var(--color-surface-container-high)',
  color: 'var(--color-on-surface-variant)',
  border: '1px solid var(--color-surface-container-high)',
}
</script>

<template>
  <div
    data-testid="annotation-list-container"
    :style="containerStyle"
  >
    <!-- Empty state -->
    <div
      v-if="props.annotations.length === 0"
      data-testid="annotation-list-empty"
      :style="emptyStyle"
    >
      <div :style="emptyTitleStyle">{{ props.emptyTitle || 'No annotations' }}</div>
      <div v-if="props.emptyDescription" :style="emptyDescriptionStyle">
        {{ props.emptyDescription }}
      </div>
      <div v-if="props.emptyActionLabel" :style="emptyActionStyle">
        {{ props.emptyActionLabel }}
      </div>
    </div>

    <!-- Annotation rows -->
    <div
      v-for="annotation in props.annotations"
      v-else
      :key="annotation.id"
      data-testid="annotation-item"
      :style="rowStyle"
    >
      <!-- Top row: dot + title + timestamp -->
      <div :style="rowTopStyle">
        <!-- Type dot -->
        <span
          data-testid="type-dot"
          :style="{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            flexShrink: '0',
            backgroundColor: typeColor(annotation.type),
          }"
        />

        <!-- Annotation title -->
        <span
          data-testid="annotation-title"
          :style="titleStyle"
        >
          {{ annotation.title }}
        </span>

        <!-- Timestamp -->
        <span
          data-testid="annotation-timestamp"
          :style="timestampStyle"
        >
          {{ formatTimestamp(annotation.timestamp) }}
        </span>
      </div>

      <!-- Optional description -->
      <div
        v-if="annotation.description"
        data-testid="annotation-description"
        :style="descriptionStyle"
      >
        {{ annotation.description }}
      </div>

      <!-- Optional tags -->
      <div
        v-if="annotation.tags && annotation.tags.length > 0"
        :style="tagsRowStyle"
      >
        <span
          v-for="tag in annotation.tags"
          :key="tag"
          data-testid="annotation-tag"
          :style="tagStyle"
        >
          {{ tag }}
        </span>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/panels/react/AnnotationListPanel.tsx
import { chartPalette, thresholdColors } from '@/utils/chartTheme'

export type AnnotationItem = {
  id: string
  title: string
  description?: string
  timestamp: string
  type: 'deploy' | 'incident' | 'config_change' | 'other'
  tags?: string[]
}

type AnnotationListPanelProps = {
  annotations?: AnnotationItem[]
  emptyTitle?: string
  emptyDescription?: string
  emptyActionLabel?: string
}

function typeColor(type: AnnotationItem['type']): string {
  if (type === 'deploy') return chartPalette[0]
  if (type === 'incident') return thresholdColors.critical
  if (type === 'config_change') return thresholdColors.warning
  return chartPalette[7]
}

function formatTimestamp(iso: string): string {
  const diffSec = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (diffSec < 60) return `${diffSec}s ago`
  const diffMin = Math.floor(diffSec / 60)
  if (diffMin < 60) return `${diffMin}m ago`
  const diffHr = Math.floor(diffMin / 60)
  if (diffHr < 24) return `${diffHr}h ago`
  return `${Math.floor(diffHr / 24)}d ago`
}

export function AnnotationListPanel({
  annotations = [],
  emptyTitle = 'No annotations',
  emptyDescription,
  emptyActionLabel,
}: AnnotationListPanelProps) {
  if (annotations.length === 0) {
    return (
      <div
        className="flex h-full w-full flex-col items-center justify-center gap-1 p-4 text-center text-sm"
        data-testid="annotation-list-empty"
        style={{ color: 'var(--color-on-surface-variant)', fontFamily: "'DM Sans', sans-serif" }}
      >
        <div className="font-semibold" style={{ color: 'var(--color-on-surface)' }}>
          {emptyTitle}
        </div>
        {emptyDescription ? <div className="max-w-sm text-xs leading-5">{emptyDescription}</div> : null}
        {emptyActionLabel ? (
          <div
            className="mt-1 text-[11px] font-semibold uppercase tracking-wide"
            style={{ color: 'var(--color-primary)' }}
          >
            {emptyActionLabel}
          </div>
        ) : null}
      </div>
    )
  }

  return (
    <div
      className="h-full w-full overflow-y-auto"
      data-testid="annotation-list-container"
      style={{ fontFamily: "'DM Sans', sans-serif" }}
    >
      {annotations.map(annotation => (
        <div
          key={annotation.id}
          data-testid="annotation-item"
          className="flex flex-col gap-1 px-3 py-2.5"
          style={{ borderBottom: '1px solid var(--color-surface-container-high)' }}
        >
          <div className="flex items-center gap-2">
            <span
              data-testid="type-dot"
              className="h-2 w-2 shrink-0 rounded-full"
              style={{ backgroundColor: typeColor(annotation.type) }}
            />
            <span
              data-testid="annotation-title"
              className="min-w-0 flex-1 truncate text-sm font-medium"
              style={{ color: 'var(--color-on-surface)' }}
            >
              {annotation.title}
            </span>
            <span
              data-testid="annotation-timestamp"
              className="shrink-0 text-xs"
              style={{ color: 'var(--color-on-surface-variant)' }}
            >
              {formatTimestamp(annotation.timestamp)}
            </span>
          </div>
          {annotation.description ? (
            <div
              data-testid="annotation-description"
              className="pl-5 text-xs"
              style={{ color: 'var(--color-on-surface-variant)' }}
            >
              {annotation.description}
            </div>
          ) : null}
          {annotation.tags && annotation.tags.length > 0 ? (
            <div className="flex flex-wrap gap-1 pl-5">
              {annotation.tags.map(tag => (
                <span
                  key={tag}
                  data-testid="annotation-tag"
                  className="rounded-full px-1.5 py-0.5 text-[11px] font-medium"
                  style={{
                    backgroundColor: 'var(--color-surface-container-high)',
                    color: 'var(--color-on-surface-variant)',
                    border: '1px solid var(--color-surface-container-high)',
                  }}
                >
                  {tag}
                </span>
              ))}
            </div>
          ) : null}
        </div>
      ))}
    </div>
  )
}
