// frontend/src/components/panels/CandlestickPanel.vue
<script setup lang="ts">
// Import ECharts candlestick components
import { CandlestickChart } from 'echarts/charts'
import { GridComponent, TooltipComponent } from 'echarts/components'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { computed, onMounted, onUnmounted, ref } from 'vue'
import VChart from 'vue-echarts'
import {
  chartAxisStyle,
  chartGridStyle,
  chartTooltipStyle,
  thresholdColors,
} from '../../utils/chartTheme'

// Register ECharts components
use([CanvasRenderer, CandlestickChart, GridComponent, TooltipComponent])

export interface CandlestickDataPoint {
  timestamp: number // Unix seconds
  open: number
  close: number
  low: number
  high: number
}

const props = defineProps<{
  data: CandlestickDataPoint[]
}>()

const chartRef = ref<typeof VChart | null>(null)

// ECharts candlestick expects timestamps in milliseconds for time axis
const xAxisData = computed(() => props.data.map((d) => d.timestamp * 1000))

// ECharts candlestick data format: [open, close, low, high]
const seriesData = computed(() =>
  props.data.map((d) => [d.open, d.close, d.low, d.high]),
)

const chartOption = computed(() => ({
  backgroundColor: 'transparent',
  grid: {
    left: '3%',
    right: '4%',
    top: '8%',
    bottom: '8%',
    containLabel: true,
  },
  tooltip: {
    trigger: 'axis' as const,
    axisPointer: {
      type: 'cross' as const,
    },
    backgroundColor: chartTooltipStyle.backgroundColor,
    borderColor: chartTooltipStyle.borderColor,
    borderWidth: 1,
    textStyle: {
      color: chartTooltipStyle.textStyle.color,
      fontFamily: chartTooltipStyle.textStyle.fontFamily,
      fontSize: chartTooltipStyle.textStyle.fontSize,
    },
    formatter: (
      params: Array<{ name: string; data: [number, number, number, number] }>,
    ) => {
      const p = params[0]
      if (!p) return ''
      const [open, close, low, high] = p.data
      return [
        `<b>${p.name}</b>`,
        `Open: ${open}`,
        `Close: ${close}`,
        `Low: ${low}`,
        `High: ${high}`,
      ].join('<br/>')
    },
  },
  xAxis: {
    type: 'time' as const,
    data: xAxisData.value,
    axisLine: {
      lineStyle: {
        color: chartAxisStyle.axisLine.lineStyle.color,
      },
    },
    axisTick: {
      show: chartAxisStyle.axisTick.show,
    },
    axisLabel: {
      color: chartAxisStyle.axisLabel.color,
      fontFamily: chartAxisStyle.axisLabel.fontFamily,
      fontSize: chartAxisStyle.axisLabel.fontSize,
    },
    splitLine: {
      lineStyle: {
        color: chartGridStyle.gridColor,
      },
    },
  },
  yAxis: {
    type: 'value' as const,
    axisLine: {
      lineStyle: {
        color: chartAxisStyle.axisLine.lineStyle.color,
      },
    },
    axisTick: {
      show: chartAxisStyle.axisTick.show,
    },
    axisLabel: {
      color: chartAxisStyle.axisLabel.color,
      fontFamily: chartAxisStyle.axisLabel.fontFamily,
      fontSize: chartAxisStyle.axisLabel.fontSize,
    },
    splitLine: {
      lineStyle: {
        color: chartGridStyle.gridColor,
      },
    },
  },
  series: [
    {
      type: 'candlestick' as const,
      data: seriesData.value,
      itemStyle: {
        // Up candle (close > open): use thresholdColors.good
        color: thresholdColors.good,
        // Down candle (close < open): use thresholdColors.critical
        color0: thresholdColors.critical,
        borderColor: thresholdColors.good,
        borderColor0: thresholdColors.critical,
      },
    },
  ],
}))

// Handle resize
let resizeObserver: ResizeObserver | null = null

onMounted(() => {
  const container = chartRef.value?.$el?.parentElement
  if (container) {
    resizeObserver = new ResizeObserver(() => {
      chartRef.value?.resize()
    })
    resizeObserver.observe(container)
  }
})

onUnmounted(() => {
  if (resizeObserver) {
    resizeObserver.disconnect()
    resizeObserver = null
  }
})
</script>

<template>
  <div class="h-full w-full">
    <VChart
      ref="chartRef"
      :option="chartOption"
      :autoresize="true"
      class="h-full w-full"
    />
  </div>
</template>

// frontend/src/components/panels/react/CandlestickPanel.tsx
import { CandlestickChart } from 'echarts/charts'
import { GridComponent, TooltipComponent } from 'echarts/components'
import { use } from 'echarts/core'
import { useMemo } from 'react'
import { useCrosshairSync } from '@/contexts/CrosshairSyncContext'
import {
  chartAxisStyle,
  chartGridStyle,
  chartTooltipStyle,
  thresholdColors,
} from '@/utils/chartTheme'
import { useRegistryEChart } from './useRegistryEChart'

use([CandlestickChart, GridComponent, TooltipComponent])

export type CandlestickDataPoint = {
  timestamp: number
  open: number
  close: number
  low: number
  high: number
}

type CandlestickPanelProps = {
  data: CandlestickDataPoint[]
}

export function CandlestickPanel({ data }: CandlestickPanelProps) {
  const { groupId } = useCrosshairSync()

  const chartOption = useMemo(() => {
    const seriesData = data.map(point => [
      point.timestamp * 1000,
      point.open,
      point.close,
      point.low,
      point.high,
    ])

    return {
      backgroundColor: 'transparent',
      grid: {
        left: '3%',
        right: '4%',
        top: '8%',
        bottom: '8%',
        containLabel: true,
      },
      tooltip: {
        trigger: 'axis' as const,
        axisPointer: { type: 'cross' as const },
        backgroundColor: chartTooltipStyle.backgroundColor,
        borderColor: chartTooltipStyle.borderColor,
        borderWidth: 1,
        textStyle: chartTooltipStyle.textStyle,
        formatter: (params: Array<{ data: [number, number, number, number, number] }>) => {
          const point = params[0]
          if (!point) return ''
          const [ts, open, close, low, high] = point.data
          const date = new Date(ts).toLocaleString()
          return [`<b>${date}</b>`, `Open: ${open}`, `Close: ${close}`, `Low: ${low}`, `High: ${high}`].join(
            '<br/>',
          )
        },
      },
      xAxis: {
        type: 'time' as const,
        ...chartAxisStyle,
        splitLine: { lineStyle: { color: chartGridStyle.gridColor } },
      },
      yAxis: {
        type: 'value' as const,
        ...chartAxisStyle,
        splitLine: { lineStyle: { color: chartGridStyle.gridColor } },
      },
      series: [
        {
          type: 'candlestick' as const,
          data: seriesData,
          itemStyle: {
            color: thresholdColors.good,
            color0: thresholdColors.critical,
            borderColor: thresholdColors.good,
            borderColor0: thresholdColors.critical,
          },
        },
      ],
    }
  }, [data])

  const containerRef = useRegistryEChart(chartOption, { groupId })

  return (
    <div className="h-full w-full" data-testid="candlestick-panel">
      <div ref={containerRef} className="h-full w-full" />
    </div>
  )
}
