// frontend/src/components/panels/DashboardListPanel.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Star } from 'lucide-vue-next'
import { chartPalette } from '../../utils/chartTheme'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DashboardLink {
  id: string
  title: string
  url: string
  tags?: string[]
  starred?: boolean
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = defineProps<{
  dashboards: DashboardLink[]
  emptyTitle?: string
  emptyDescription?: string
  emptyActionLabel?: string
}>()

// ---------------------------------------------------------------------------
// Computed styles
// ---------------------------------------------------------------------------

const containerStyle = computed(() => ({
  overflowY: 'auto' as const,
  height: '100%',
  width: '100%',
  fontFamily: "'DM Sans', sans-serif",
  backgroundColor: 'transparent',
}))

const emptyStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  alignItems: 'center',
  justifyContent: 'center',
  gap: '0.35rem',
  height: '100%',
  color: 'var(--color-on-surface-variant)',
  fontSize: '0.875rem',
  textAlign: 'center' as const,
  padding: '1rem',
}

const emptyTitleStyle = {
  color: 'var(--color-on-surface)',
  fontWeight: '600',
}

const emptyDescriptionStyle = {
  maxWidth: '22rem',
  fontSize: '0.75rem',
  lineHeight: '1.35',
}

const emptyActionStyle = {
  marginTop: '0.25rem',
  fontSize: '0.6875rem',
  fontWeight: '600',
  color: 'var(--color-primary)',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.04em',
}

const rowStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '0.25rem',
  padding: '0.625rem 0.75rem',
  borderBottom: '1px solid var(--color-surface-container-high)',
}

const rowTopStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
}

const linkStyle = {
  flex: '1',
  fontSize: '0.875rem',
  fontWeight: '500',
  color: 'var(--color-on-surface)',
  textDecoration: 'none',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap' as const,
}

const tagsRowStyle = {
  display: 'flex',
  flexWrap: 'wrap' as const,
  gap: '0.25rem',
  paddingLeft: '1.5rem', // align under title (past the star icon)
}

const tagStyle = {
  fontSize: '0.6875rem',
  fontWeight: '500',
  padding: '0.125rem 0.375rem',
  borderRadius: '9999px',
  backgroundColor: 'var(--color-surface-container-high)',
  color: 'var(--color-on-surface-variant)',
  border: '1px solid var(--color-surface-container-high)',
}

function starStyle(starred?: boolean) {
  if (starred) {
    return {
      color: chartPalette[4], // Signal Brass
      fill: chartPalette[4],
      flexShrink: '0',
    }
  }
  return {
    color: 'var(--color-on-surface-variant)',
    flexShrink: '0',
  }
}
</script>

<template>
  <div
    data-testid="dashboard-list-container"
    :style="containerStyle"
  >
    <!-- Empty state -->
    <div
      v-if="props.dashboards.length === 0"
      data-testid="dashboard-list-empty"
      :style="emptyStyle"
    >
      <div :style="emptyTitleStyle">{{ props.emptyTitle || 'No dashboards' }}</div>
      <div v-if="props.emptyDescription" :style="emptyDescriptionStyle">
        {{ props.emptyDescription }}
      </div>
      <div v-if="props.emptyActionLabel" :style="emptyActionStyle">
        {{ props.emptyActionLabel }}
      </div>
    </div>

    <!-- Dashboard rows -->
    <div
      v-for="dashboard in props.dashboards"
      v-else
      :key="dashboard.id"
      data-testid="dashboard-item"
      :style="rowStyle"
    >
      <!-- Top row: star + link -->
      <div :style="rowTopStyle">
        <!-- Star icon -->
        <span
          data-testid="star-icon"
          :style="starStyle(dashboard.starred)"
        >
          <Star :size="14" :fill="dashboard.starred ? chartPalette[4] : 'none'" />
        </span>

        <!-- Dashboard title as link -->
        <a
          data-testid="dashboard-link"
          :href="dashboard.url"
          :style="linkStyle"
        >
          {{ dashboard.title }}
        </a>
      </div>

      <!-- Optional tags -->
      <div
        v-if="dashboard.tags && dashboard.tags.length > 0"
        :style="tagsRowStyle"
      >
        <span
          v-for="tag in dashboard.tags"
          :key="tag"
          data-testid="dashboard-tag"
          :style="tagStyle"
        >
          {{ tag }}
        </span>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/panels/react/DashboardListPanel.tsx
import { Star } from 'lucide-react'
import { chartPalette } from '@/utils/chartTheme'

export type DashboardLink = {
  id: string
  title: string
  url: string
  tags?: string[]
  starred?: boolean
}

type DashboardListPanelProps = {
  dashboards?: DashboardLink[]
  emptyTitle?: string
  emptyDescription?: string
  emptyActionLabel?: string
}

export function DashboardListPanel({
  dashboards = [],
  emptyTitle = 'No dashboards',
  emptyDescription,
  emptyActionLabel,
}: DashboardListPanelProps) {
  if (dashboards.length === 0) {
    return (
      <div
        className="flex h-full w-full flex-col items-center justify-center gap-1 p-4 text-center text-sm"
        data-testid="dashboard-list-empty"
        style={{ color: 'var(--color-on-surface-variant)', fontFamily: "'DM Sans', sans-serif" }}
      >
        <div className="font-semibold" style={{ color: 'var(--color-on-surface)' }}>
          {emptyTitle}
        </div>
        {emptyDescription ? <div className="max-w-sm text-xs leading-5">{emptyDescription}</div> : null}
        {emptyActionLabel ? (
          <div
            className="mt-1 text-[11px] font-semibold uppercase tracking-wide"
            style={{ color: 'var(--color-primary)' }}
          >
            {emptyActionLabel}
          </div>
        ) : null}
      </div>
    )
  }

  return (
    <div
      className="h-full w-full overflow-y-auto"
      data-testid="dashboard-list-container"
      style={{ fontFamily: "'DM Sans', sans-serif" }}
    >
      {dashboards.map(dashboard => (
        <div
          key={dashboard.id}
          data-testid="dashboard-item"
          className="flex flex-col gap-1 px-3 py-2.5"
          style={{ borderBottom: '1px solid var(--color-surface-container-high)' }}
        >
          <div className="flex items-center gap-2">
            <span data-testid="star-icon" className="shrink-0">
              <Star
                size={14}
                fill={dashboard.starred ? chartPalette[4] : 'none'}
                color={dashboard.starred ? chartPalette[4] : 'var(--color-on-surface-variant)'}
              />
            </span>
            <a
              data-testid="dashboard-link"
              href={dashboard.url}
              className="min-w-0 flex-1 truncate text-sm font-medium no-underline"
              style={{ color: 'var(--color-on-surface)' }}
            >
              {dashboard.title}
            </a>
          </div>
          {dashboard.tags && dashboard.tags.length > 0 ? (
            <div className="flex flex-wrap gap-1 pl-6">
              {dashboard.tags.map(tag => (
                <span
                  key={tag}
                  data-testid="dashboard-tag"
                  className="rounded-full px-1.5 py-0.5 text-[11px] font-medium"
                  style={{
                    backgroundColor: 'var(--color-surface-container-high)',
                    color: 'var(--color-on-surface-variant)',
                    border: '1px solid var(--color-surface-container-high)',
                  }}
                >
                  {tag}
                </span>
              ))}
            </div>
          ) : null}
        </div>
      ))}
    </div>
  )
}
